<?php

declare(strict_types=1);

return [
    [
        'slug' => 'fb_story_announcement',
        'category' => 'product_launch',
        'name' => 'إعلان سريع',
        'description' => 'استقطب الانتباه لتحديث جديد عبر ستوري فيسبوك يدوم 24 ساعة.',
        'content' => "تنويه من {{brand_name}}.\n\n[أبرز نقطة بسطر واحد]\n\nالرابط في البروفايل.",
        'image_count' => 1,
        'image_keywords' => ['announcement', 'launch'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_promo',
        'category' => 'promotion',
        'name' => 'عرض خاطف',
        'description' => 'عرض محدود المدة بصيغة ستوري.',
        'content' => "اليوم فقط.\n\nخصم [نسبة الخصم]% في {{brand_name}}.\n\nاضغط للتسوق.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'urgency'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_question',
        'category' => 'engagement',
        'name' => 'سؤال سريع',
        'description' => 'اسأل متابعينك سؤالاً لتحفيز الردود والتفاعل.',
        'content' => "سؤال سريع.\n\n[سؤال لجمهورك]\n\nرد على هذا الستوري.",
        'image_count' => 1,
        'image_keywords' => ['question', 'engagement'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_new_drop',
        'category' => 'product_launch',
        'name' => 'إطلاق جديد',
        'description' => 'لمّح لمنتج جديد بإشارة مرئية سريعة.',
        'content' => "وصل أخيراً.\n\n[اسم المنتج] من {{brand_name}}.\n\nاضغط لتشوفه.",
        'image_count' => 1,
        'image_keywords' => ['new product', 'unboxing'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_preorder',
        'category' => 'product_launch',
        'name' => 'الطلب المسبق متاح',
        'description' => 'افتح باب الطلب المسبق برسالة ستوري قصيرة.',
        'content' => "الطلب المسبق متاح الآن.\n\n[المنتج] يشحن بتاريخ [التاريخ].\n\nالرابط في البايو.",
        'image_count' => 1,
        'image_keywords' => ['preorder', 'product'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_launch_day',
        'category' => 'product_launch',
        'name' => 'يوم الإطلاق',
        'description' => 'أعلن الإطلاق الرسمي بدعوة سريعة للضغط.',
        'content' => "متاح الآن.\n\n[المنتج] يشحن اليوم.\n\nاضغط واطلب نسختك.",
        'image_count' => 1,
        'image_keywords' => ['launch', 'product reveal'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_back_in_stock',
        'category' => 'product_launch',
        'name' => 'توفر من جديد',
        'description' => 'أخبر متابعينك أن منتج نفد رجع متوفر.',
        'content' => "توفر من جديد.\n\n[المنتج] في {{brand_name}}.\n\nينفد بسرعة، اضغط واطلع عليه.",
        'image_count' => 1,
        'image_keywords' => ['restock', 'available'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bogo',
        'category' => 'promotion',
        'name' => 'اشترِ واحد واحصل على الثاني مجاناً',
        'description' => 'روّج لعرض اشترِ واحد واحصل على الثاني مجاناً بصيغة ستوري.',
        'content' => "اشترِ 1 واحصل على 1 مجاناً.\n\nهذا الأسبوع في {{brand_name}}.\n\nاضغط للتسوق.",
        'image_count' => 1,
        'image_keywords' => ['bogo', 'sale'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_free_shipping',
        'category' => 'promotion',
        'name' => 'شحن مجاني',
        'description' => 'روّج لفترة شحن مجاني محدودة.',
        'content' => "شحن مجاني.\n\n48 ساعة فقط في {{brand_name}}.\n\nاستخدم كود [الكود].",
        'image_count' => 1,
        'image_keywords' => ['shipping', 'delivery box'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_last_chance',
        'category' => 'promotion',
        'name' => 'آخر فرصة للتخفيضات',
        'description' => 'تذكير أخير قبل انتهاء الخصم.',
        'content' => "آخر فرصة.\n\nخصم [نسبة الخصم]% ينتهي الليلة.\n\nاضغط وتسوق من {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['countdown', 'sale ending'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_coupon_drop',
        'category' => 'promotion',
        'name' => 'كود خصم جديد',
        'description' => 'شارك كود خصم في ستوري يدوم 24 ساعة.',
        'content' => "الكود [الكود].\n\nخصم [نسبة الخصم]% في {{brand_name}}.\n\nينتهي خلال 24 ساعة.",
        'image_count' => 1,
        'image_keywords' => ['coupon', 'promo code'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_quick_tip',
        'category' => 'educational',
        'name' => 'نصيحة سريعة',
        'description' => 'شارك نصيحة مفيدة واحدة.',
        'content' => "نصيحة سريعة.\n\n[نصيحة عملية واحدة]\n\nاحفظ هذا الستوري.",
        'image_count' => 1,
        'image_keywords' => ['tip', 'advice'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_did_you_know',
        'category' => 'educational',
        'name' => 'هل تعلم',
        'description' => 'فاجئ متابعينك بمعلومة سريعة.',
        'content' => "هل تعلم؟\n\n[معلومة مفاجئة]\n\nالمزيد في مدونة {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['fact', 'lightbulb'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_myth_buster',
        'category' => 'educational',
        'name' => 'تصحيح معلومة شائعة',
        'description' => 'صحّح معلومة خاطئة شائعة بسرعة.',
        'content' => "الشائع: [الاعتقاد الشائع].\n\nالحقيقة: [الحقيقة].\n\nاضغط لتعرف السبب.",
        'image_count' => 1,
        'image_keywords' => ['myth', 'truth'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_one_minute_lesson',
        'category' => 'educational',
        'name' => 'درس بدقيقة واحدة',
        'description' => 'درس مختصر مع دعوة سريعة للضغط.',
        'content' => "درس بـ60 ثانية.\n\n[الموضوع] من {{brand_name}}.\n\nاضغط للمشاهدة.",
        'image_count' => 1,
        'image_keywords' => ['lesson', 'teaching'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_workspace',
        'category' => 'behind_the_scenes',
        'name' => 'خلف الكواليس',
        'description' => 'أرِ متابعينك مكان العمل خلف الكواليس.',
        'content' => "اليوم في {{brand_name}}.\n\n[ما يحدث الآن]\n\nاضغط للمزيد.",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'office'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_team',
        'category' => 'behind_the_scenes',
        'name' => 'تعرّف على الفريق',
        'description' => 'قدّم أحد أعضاء الفريق بسرعة.',
        'content' => "تعرّف على [الاسم].\n\n[الدور في {{brand_name}}]\n\nاضغط وسلّم عليه.",
        'image_count' => 1,
        'image_keywords' => ['team', 'employee'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_process',
        'category' => 'behind_the_scenes',
        'name' => 'كيف يُصنع',
        'description' => 'لمحة سريعة عن طريقة صنع المنتج.',
        'content' => "كيف يُصنع [المنتج].\n\nالخطوة [رقم الخطوة] في {{brand_name}}.\n\nاضغط لمشاهدة المقطع كامل.",
        'image_count' => 1,
        'image_keywords' => ['production', 'process'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_packing',
        'category' => 'behind_the_scenes',
        'name' => 'تجهيز الطلبات',
        'description' => 'أرِ الطلبات وهي تخرج للشحن.',
        'content' => "نجهّز الطلبات.\n\n[العدد] طلب يخرج اليوم.\n\nشكراً لدعمكم.",
        'image_count' => 1,
        'image_keywords' => ['packing', 'shipping'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_customer_quote',
        'category' => 'testimonial',
        'name' => 'اقتباس من عميل',
        'description' => 'اعرض اقتباساً قصيراً من أحد العملاء.',
        'content' => "\"[اقتباس العميل]\"\n\n- [الاسم]\n\nاضغط لقراءة المزيد.",
        'image_count' => 1,
        'image_keywords' => ['quote', 'review'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_five_star',
        'category' => 'testimonial',
        'name' => 'تقييم 5 نجوم',
        'description' => 'سلّط الضوء على تقييم بخمس نجوم.',
        'content' => "5 نجوم.\n\n\"[تقييم قصير]\"، [الاسم]\n\nالمزيد في {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['five stars', 'review'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_before_after',
        'category' => 'testimonial',
        'name' => 'قبل وبعد',
        'description' => 'أرِ صورة قبل وبعد مع دعوة واحدة للتفاعل.',
        'content' => "قبل. بعد.\n\n[اسم العميل] يستخدم {{brand_name}}.\n\nاضغط لتعرف القصة.",
        'image_count' => 1,
        'image_keywords' => ['before after', 'transformation'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_industry_trend',
        'category' => 'industry_tip',
        'name' => 'اتجاه في المجال',
        'description' => 'شارك ملاحظة سريعة عن اتجاه في المجال.',
        'content' => "رصد اتجاه.\n\n[اتجاه المجال بسطر واحد]\n\nاضغط لمعرفة رأينا.",
        'image_count' => 1,
        'image_keywords' => ['trend', 'industry'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_pro_hack',
        'category' => 'industry_tip',
        'name' => 'حيلة احترافية',
        'description' => 'شارك حيلة احترافية سريعة.',
        'content' => "حيلة احترافية.\n\n[حيلة بسطر واحد]\n\nالمزيد من النصائح في {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['hack', 'shortcut'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_mistake_to_avoid',
        'category' => 'industry_tip',
        'name' => 'خطأ تجنّبه',
        'description' => 'نبّه لخطأ شائع.',
        'content' => "توقف عن هذا.\n\n[خطأ شائع]\n\nاضغط لتعرف الحل.",
        'image_count' => 1,
        'image_keywords' => ['warning', 'mistake'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_event_save_date',
        'category' => 'event',
        'name' => 'احجز التاريخ',
        'description' => 'شارك تذكيراً بحجز التاريخ في ستوري لمدة 24 ساعة.',
        'content' => "احجز التاريخ.\n\n[الفعالية] بتاريخ [التاريخ].\n\nأكد حضورك عبر البايو.",
        'image_count' => 1,
        'image_keywords' => ['calendar', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_event_today',
        'category' => 'event',
        'name' => 'فعالية اليوم',
        'description' => 'تذكير بفعالية في نفس اليوم.',
        'content' => "اليوم.\n\n[الفعالية] الساعة [الوقت].\n\nاضغط للرابط.",
        'image_count' => 1,
        'image_keywords' => ['event', 'live'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_live_starting',
        'category' => 'event',
        'name' => 'بث مباشر الآن',
        'description' => 'ادعُ متابعينك للانضمام للبث المباشر.',
        'content' => "بث مباشر بعد قليل.\n\n[الموضوع] خلال [عدد الدقائق] دقيقة.\n\nاضغط وانضم لـ{{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['live stream', 'broadcast'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_event_recap',
        'category' => 'event',
        'name' => 'ملخص الفعالية',
        'description' => 'ملخص سريع لليوم التالي للفعالية.',
        'content' => "كانت هذي فعالية [الفعالية].\n\nشكراً لحضوركم.\n\nالملخص كامل على الصفحة.",
        'image_count' => 1,
        'image_keywords' => ['event recap', 'crowd'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_poll_this_or_that',
        'category' => 'engagement',
        'name' => 'هذا أو ذاك',
        'description' => 'ستوري استطلاع بخيارين.',
        'content' => "[الخيار أ] أو [الخيار ب]؟\n\nرد باختيارك.\n\nنقرأ كل رد.",
        'image_count' => 1,
        'image_keywords' => ['poll', 'choice'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_dm_us',
        'category' => 'engagement',
        'name' => 'راسلنا',
        'description' => 'ادعُ متابعينك لإرسال رسالة.',
        'content' => "راسلنا.\n\n[سبب مراسلة {{brand_name}}]\n\nنرد بسرعة.",
        'image_count' => 1,
        'image_keywords' => ['message', 'chat'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_caption_this',
        'category' => 'engagement',
        'name' => 'اكتب تعليق',
        'description' => 'سؤال مفتوح لكتابة تعليق.',
        'content' => "اكتب لها تعليق.\n\n[سياق الصورة]\n\nرد بأحسن تعليق.",
        'image_count' => 1,
        'image_keywords' => ['fun', 'reaction'],
        'slides' => null,
    ],
];
