<?php

declare(strict_types=1);

return [
    [
        'slug' => 'story_announcement',
        'category' => 'product_launch',
        'name' => 'إعلان سريع',
        'description' => 'لفت الانتباه لإطلاق أو تحديث جديد عبر ستوري مدته 24 ساعة.',
        'content' => "أخبار كبيرة في {{brand_name}}.\n\nاضغط على الرابط وشوف الجديد.",
        'image_count' => 1,
        'image_keywords' => ['announcement', 'launch'],
        'slides' => null,
    ],
    [
        'slug' => 'story_poll_question',
        'category' => 'engagement',
        'name' => 'سؤال استطلاع',
        'description' => 'استخدم الستوري لطرح سؤال سريع وتفاعل مع متابعينك.',
        'content' => "إيش أهم شي عند اختيار [المنتج/الخدمة]؟\n\nاضغط للتصويت.",
        'image_count' => 1,
        'image_keywords' => ['question', 'engagement'],
        'slides' => null,
    ],
    [
        'slug' => 'story_flash_promo',
        'category' => 'promotion',
        'name' => 'عرض خاطف',
        'description' => 'عرض لفترة محدودة بصيغة ستوري يخلق إحساس بالاستعجال.',
        'content' => "24 ساعة بس.\n\nخصم [الخصم]% في {{brand_name}}.\n\nاسحب للأعلى.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'urgency'],
        'slides' => null,
    ],
    [
        'slug' => 'story_product_drop',
        'category' => 'product_launch',
        'name' => 'إطلاق منتج جديد',
        'description' => 'أعلن عن منتج جديد ينزل اليوم.',
        'content' => "صار متاح الحين.\n\n[اسم المنتج] لتوه نزل.\n\nالرابط في البايو.",
        'image_count' => 1,
        'image_keywords' => ['product', 'launch', 'new'],
        'slides' => null,
    ],
    [
        'slug' => 'story_feature_shipped',
        'category' => 'product_launch',
        'name' => 'ميزة جديدة أطلقناها',
        'description' => 'خبّر متابعينك عن ميزة جديدة لتوك أطلقتها.',
        'content' => "لتونا أطلقنا [الميزة].\n\nروح جربها.",
        'image_count' => 1,
        'image_keywords' => ['update', 'feature', 'app'],
        'slides' => null,
    ],
    [
        'slug' => 'story_waitlist_open',
        'category' => 'product_launch',
        'name' => 'قائمة الانتظار مفتوحة',
        'description' => 'ادعِ متابعينك للانضمام لقائمة الانتظار.',
        'content' => "قائمة الانتظار مفتوحة.\n\n[عدد الأماكن] مقعد متبقي.\n\nالرابط في البايو.",
        'image_count' => 1,
        'image_keywords' => ['waitlist', 'signup'],
        'slides' => null,
    ],
    [
        'slug' => 'story_preorder_live',
        'category' => 'product_launch',
        'name' => 'الطلب المسبق متاح',
        'description' => 'شجّع على الطلب المسبق لمنتج قادم.',
        'content' => "الطلب المسبق مفتوح.\n\nالشحن بتاريخ [التاريخ].\n\nاضغط علشان تحجز نسختك.",
        'image_count' => 1,
        'image_keywords' => ['preorder', 'product'],
        'slides' => null,
    ],
    [
        'slug' => 'story_weekend_sale',
        'category' => 'promotion',
        'name' => 'تخفيضات نهاية الأسبوع',
        'description' => 'روّج لتخفيضات سريعة في نهاية الأسبوع.',
        'content' => "تخفيضات نهاية الأسبوع.\n\nخصم [الخصم]% على كل شي.\n\nتنتهي يوم الأحد.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'weekend', 'discount'],
        'slides' => null,
    ],
    [
        'slug' => 'story_code_drop',
        'category' => 'promotion',
        'name' => 'كود خصم جديد',
        'description' => 'شارك كود يقدر متابعينك يستخدمونه عند الدفع.',
        'content' => "استخدم [الكود] عند الدفع.\n\nخصم [الخصم]%.\n\nصالح لين [التاريخ].",
        'image_count' => 1,
        'image_keywords' => ['coupon', 'code', 'discount'],
        'slides' => null,
    ],
    [
        'slug' => 'story_last_chance',
        'category' => 'promotion',
        'name' => 'آخر فرصة',
        'description' => 'تذكير أخير قبل ما ينتهي العرض.',
        'content' => "آخر فرصة.\n\n[العرض] ينتهي منتصف الليل.",
        'image_count' => 1,
        'image_keywords' => ['deadline', 'sale', 'urgent'],
        'slides' => null,
    ],
    [
        'slug' => 'story_bundle_deal',
        'category' => 'promotion',
        'name' => 'باقة مميزة',
        'description' => 'روّج لباقة بسعر أقل.',
        'content' => "باقة مميزة.\n\n[المنتج أ] + [المنتج ب] بسعر [السعر].\n\nاضغط واقتنيها.",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'deal', 'product'],
        'slides' => null,
    ],
    [
        'slug' => 'story_quick_tip',
        'category' => 'educational',
        'name' => 'نصيحة سريعة',
        'description' => 'شارك نصيحة قصيرة على الشاشة.',
        'content' => "نصيحة سريعة:\n\n[نصيحة قصيرة وعملية].",
        'image_count' => 1,
        'image_keywords' => ['tip', 'advice', 'learning'],
        'slides' => null,
    ],
    [
        'slug' => 'story_did_you_know',
        'category' => 'educational',
        'name' => 'هل تعلم',
        'description' => 'شارك معلومة مثيرة للاهتمام.',
        'content' => "هل تعلم؟\n\n[معلومة مثيرة عن مجالك].",
        'image_count' => 1,
        'image_keywords' => ['fact', 'knowledge'],
        'slides' => null,
    ],
    [
        'slug' => 'story_common_mistake',
        'category' => 'educational',
        'name' => 'خطأ شائع',
        'description' => 'نبّه على خطأ شائع يقع فيه جمهورك.',
        'content' => "بطّل تسوي [الخطأ الشائع].\n\nسوّ [الطريقة الأفضل] بدالها.",
        'image_count' => 1,
        'image_keywords' => ['mistake', 'advice', 'tip'],
        'slides' => null,
    ],
    [
        'slug' => 'story_one_word_lesson',
        'category' => 'educational',
        'name' => 'درس بكلمة وحدة',
        'description' => 'كلمة وحدة تتبعها توضيح قصير للسبب.',
        'content' => "[كلمة واحدة].\n\nهذا الفرق بين [النتيجة أ] و[النتيجة ب].",
        'image_count' => 1,
        'image_keywords' => ['lesson', 'word', 'idea'],
        'slides' => null,
    ],
    [
        'slug' => 'story_workspace_peek',
        'category' => 'behind_the_scenes',
        'name' => 'لمحة عن مكان الشغل',
        'description' => 'لقطة سريعة لمكان اللي يصير فيه الشغل.',
        'content' => "وين يصير الشغل.\n\n[وصف قصير عن مكانك].",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'desk', 'office'],
        'slides' => null,
    ],
    [
        'slug' => 'story_meet_the_team',
        'category' => 'behind_the_scenes',
        'name' => 'تعرف على الفريق',
        'description' => 'عرّف بعضو من الفريق بسطر وحد.',
        'content' => "تعرف على [الاسم].\n\n[دورهم في {{brand_name}}].",
        'image_count' => 1,
        'image_keywords' => ['team', 'people', 'portrait'],
        'slides' => null,
    ],
    [
        'slug' => 'story_in_progress',
        'category' => 'behind_the_scenes',
        'name' => 'قيد التنفيذ',
        'description' => 'اعرض شي لسه ما خلص.',
        'content' => "قيد التنفيذ.\n\n[اللي تشتغل عليه الحين].",
        'image_count' => 1,
        'image_keywords' => ['process', 'work', 'progress'],
        'slides' => null,
    ],
    [
        'slug' => 'story_packing_orders',
        'category' => 'behind_the_scenes',
        'name' => 'تغليف الطلبات',
        'description' => 'اعرض الطلبات وهي طالعة للشحن.',
        'content' => "طلبات اليوم.\n\nشكراً على ثقتكم في {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['packaging', 'orders', 'shipping'],
        'slides' => null,
    ],
    [
        'slug' => 'story_customer_quote',
        'category' => 'testimonial',
        'name' => 'اقتباس من عميل',
        'description' => 'شارك اقتباس قصير من عميل على الشاشة.',
        'content' => "\"[اقتباس قصير من العميل].\"\n\n- [اسم العميل]",
        'image_count' => 1,
        'image_keywords' => ['testimonial', 'review', 'quote'],
        'slides' => null,
    ],
    [
        'slug' => 'story_review_screenshot',
        'category' => 'testimonial',
        'name' => 'صورة تقييم',
        'description' => 'أعد نشر صورة تقييم رائع.',
        'content' => "تقييمات مثل هذي تفرحنا بجد.\n\nشكراً لك، [الاسم الأول للعميل].",
        'image_count' => 1,
        'image_keywords' => ['review', 'screenshot', 'feedback'],
        'slides' => null,
    ],
    [
        'slug' => 'story_before_after_user',
        'category' => 'testimonial',
        'name' => 'قبل وبعد لعميل',
        'description' => 'سلّط الضوء على نتيجة عميل.',
        'content' => '[الاسم الأول للعميل] انتقل من [قبل] إلى [بعد] خلال [المدة].',
        'image_count' => 1,
        'image_keywords' => ['result', 'transformation', 'customer'],
        'slides' => null,
    ],
    [
        'slug' => 'story_industry_myth',
        'category' => 'industry_tip',
        'name' => 'خرافة شائعة في المجال',
        'description' => 'فنّد اعتقاد شائع في مجالك.',
        'content' => "خرافة: [الاعتقاد الشائع].\n\nالحقيقة: [الحقيقة].",
        'image_count' => 1,
        'image_keywords' => ['myth', 'industry', 'truth'],
        'slides' => null,
    ],
    [
        'slug' => 'story_industry_stat',
        'category' => 'industry_tip',
        'name' => 'إحصائية من المجال',
        'description' => 'شارك إحصائية توقف عندها المتابعين.',
        'content' => "[الإحصائية].\n\nعشان كذا أسسنا {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['statistic', 'data', 'industry'],
        'slides' => null,
    ],
    [
        'slug' => 'story_tool_we_use',
        'category' => 'industry_tip',
        'name' => 'أداة نستخدمها',
        'description' => 'رشّح أداة يقدر جمهورك يجربها.',
        'content' => "أداة نستخدمها كل يوم:\n\n[اسم الأداة].\n\nوهذا السبب: [سبب قصير].",
        'image_count' => 1,
        'image_keywords' => ['tool', 'software', 'recommendation'],
        'slides' => null,
    ],
    [
        'slug' => 'story_red_flag',
        'category' => 'industry_tip',
        'name' => 'علامة تحذير',
        'description' => 'حذّر متابعينك من علامة تحذير في مجالك.',
        'content' => "علامة تحذير في [المجال]:\n\n[العلامة اللي لازم تنتبه لها].",
        'image_count' => 1,
        'image_keywords' => ['warning', 'industry', 'advice'],
        'slides' => null,
    ],
    [
        'slug' => 'story_event_today',
        'category' => 'event',
        'name' => 'فعالية اليوم',
        'description' => 'تذكير سريع لفعالية تصير اليوم.',
        'content' => "الليلة.\n\n[اسم الفعالية] الساعة [الوقت].\n\nاضغط للرابط.",
        'image_count' => 1,
        'image_keywords' => ['event', 'reminder'],
        'slides' => null,
    ],
    [
        'slug' => 'story_event_countdown',
        'category' => 'event',
        'name' => 'عد تنازلي للفعالية',
        'description' => 'اصنع ترقب بعد تنازلي.',
        'content' => "باقي [X] يوم على [اسم الفعالية].\n\nرد بكلمة GO عشان نذكّرك.",
        'image_count' => 1,
        'image_keywords' => ['countdown', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'story_live_now',
        'category' => 'event',
        'name' => 'بث مباشر الحين',
        'description' => 'خبّر متابعينك إنك بث مباشر أو على المسرح.',
        'content' => "بث مباشر الحين.\n\n[الموضوع أو المكان].\n\nتعال سلّم علينا.",
        'image_count' => 1,
        'image_keywords' => ['live', 'streaming', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'story_event_recap',
        'category' => 'event',
        'name' => 'ملخص الفعالية',
        'description' => 'ملخص سريع بعد ما تنتهي الفعالية.',
        'content' => "[اسم الفعالية] خلصت.\n\nشكراً لكل من حضر.",
        'image_count' => 1,
        'image_keywords' => ['event', 'recap', 'crowd'],
        'slides' => null,
    ],
    [
        'slug' => 'story_this_or_that',
        'category' => 'engagement',
        'name' => 'هذا ولا ذاك',
        'description' => 'استطلاع بخيارين للتصويت السريع.',
        'content' => "[الخيار أ] ولا [الخيار ب]؟\n\nاضغط للتصويت.",
        'image_count' => 1,
        'image_keywords' => ['poll', 'choice', 'vote'],
        'slides' => null,
    ],
    [
        'slug' => 'story_question_box',
        'category' => 'engagement',
        'name' => 'صندوق الأسئلة',
        'description' => 'افتح المجال للأسئلة.',
        'content' => "اسألني أي شي عن [الموضوع].\n\nرد بسؤالك.",
        'image_count' => 1,
        'image_keywords' => ['questions', 'ama', 'conversation'],
        'slides' => null,
    ],
    [
        'slug' => 'story_emoji_slider',
        'category' => 'engagement',
        'name' => 'منزلق الإيموجي',
        'description' => 'استخدم ملصق المنزلق لقياس شعور.',
        'content' => "قد إيش متحمس لـ[الشي]؟\n\nحرّك المنزلق.",
        'image_count' => 1,
        'image_keywords' => ['slider', 'reaction', 'engagement'],
        'slides' => null,
    ],
    [
        'slug' => 'story_dm_prompt',
        'category' => 'engagement',
        'name' => 'دعوة للمراسلة',
        'description' => 'شجّع متابعينك يرسلون كلمة معينة بالخاص.',
        'content' => "تبي [المورد]؟\n\nرد بـ[الكلمة] وبأرسلها لك.",
        'image_count' => 1,
        'image_keywords' => ['dm', 'message', 'engagement'],
        'slides' => null,
    ],
];
