<?php

declare(strict_types=1);

return [
    [
        'slug' => 'limited_time_offer_feed',
        'category' => 'promotion',
        'name' => 'عرض لفترة محدودة',
        'description' => 'روّج لعرض محدود بالوقت على فيد إنستقرام.',
        'content' => "⏰ لا تفوّته. {{brand_name}} يقدّم خصم [discount]% على [product/service]، اليوم فقط.\n\nاضغط على الرابط في البايو واحصل على نصيبك قبل ما ينتهي.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'offer', 'shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'team_behind_the_scenes_feed',
        'category' => 'behind_the_scenes',
        'name' => 'خلف الكواليس مع الفريق',
        'description' => 'أضف لمسة إنسانية لعلامتك بإظهار الفريق أثناء العمل.',
        'content' => "هذا شكل يوم عادي في {{brand_name}}. 👀\n\nنؤمن إن الشغل المتقن يصير لما الناس تحس إنها في مكانها. هذي لمحة من خلف الكواليس.\n\n#{{brand_name}} #BehindTheScenes",
        'image_count' => 1,
        'image_keywords' => ['office', 'team', 'workspace'],
        'slides' => null,
    ],
    [
        'slug' => 'new_product_drop_feed',
        'category' => 'product_launch',
        'name' => 'إطلاق منتج جديد',
        'description' => 'أعلن عن إطلاق منتج جديد على الفيد.',
        'content' => "وصل أخيراً. [Product name] وصل لتوه إلى {{brand_name}}.\n\nصرفنا عليه [months/weeks]. كل تفصيلة فيه اختبرها الفريق قبل ما يطلع للناس.\n\nاضغط على الرابط في البايو وكن من أول اللي يجربونه.",
        'image_count' => 1,
        'image_keywords' => ['product', 'launch', 'unboxing'],
        'slides' => null,
    ],
    [
        'slug' => 'pre_order_announcement_feed',
        'category' => 'product_launch',
        'name' => 'إعلان الطلب المسبق',
        'description' => 'افتح باب الطلب المسبق لمنتج قادم.',
        'content' => "الطلب المسبق متاح الآن. [Product name] يشحن بتاريخ [date].\n\nالدفعة الأولى محدودة بـ [number] قطعة فقط. وبعد ما تنتهي، الدفعة الثانية ما تشحن إلا بتاريخ [later date].\n\nاحجز نصيبك عبر الرابط في البايو.",
        'image_count' => 1,
        'image_keywords' => ['product', 'package', 'box'],
        'slides' => null,
    ],
    [
        'slug' => 'feature_highlight_launch_feed',
        'category' => 'product_launch',
        'name' => 'تسليط الضوء على ميزة',
        'description' => 'سلّط الضوء على ميزة معينة في منتج جديد.',
        'content' => "الشي اللي نفتخر فيه أكثر شي في [product name]: [specific feature].\n\nاحتجنا [number] نموذج أولي عشان نوصله للشكل الصح. المجرّبون الأوائل قالوا لنا إنه غيّر طريقة [use case] عندهم، فكملنا التطوير لين صار واضح.\n\nشوفه شغال عبر الرابط في البايو.",
        'image_count' => 1,
        'image_keywords' => ['product', 'detail', 'closeup'],
        'slides' => null,
    ],
    [
        'slug' => 'product_restock_feed',
        'category' => 'product_launch',
        'name' => 'إعادة تعبئة المخزون',
        'description' => 'أعلن عن رجوع منتج شائع للمخزون.',
        'content' => "رجع للمخزون. [Product name] نفد خلال [time period] آخر مرة، فسوّينا كمية أكبر.\n\nإذا فاتتك أول مرة، هذي فرصتك. الكمية محدودة مرة ثانية، ونتوقع تنفد بسرعة زي قبل.\n\nاحصل على نصيبك عبر الرابط في البايو.",
        'image_count' => 1,
        'image_keywords' => ['product', 'shelf', 'inventory'],
        'slides' => null,
    ],
    [
        'slug' => 'flash_sale_feed',
        'category' => 'promotion',
        'name' => 'تخفيضات خاطفة',
        'description' => 'أوجد إحساس بالإلحاح بتخفيضات خاطفة قصيرة.',
        'content' => "تخفيضات خاطفة. خصم [Discount]% على كل شي لمدة [hours] ساعة قادمة.\n\nمافي حاجة لكود عند الدفع. الخصم مفعّل تلقائياً على كل الموقع.\n\nالرابط في البايو. ضبط منبّه أحسن.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'bundle_deal_feed',
        'category' => 'promotion',
        'name' => 'عرض الباقة',
        'description' => 'روّج لعرض باقة تجمع أكثر من منتج.',
        'content' => "اشترِ [item A] و[item B] مع بعض ووفّر [amount].\n\nهذا نفس الكومبو اللي يستخدمه فريقنا كل أسبوع، فجمعناه لكم كباقة واحدة. أرخص من شرائهم كل واحد لحاله.\n\nالرابط في البايو.",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'products', 'gift'],
        'slides' => null,
    ],
    [
        'slug' => 'free_shipping_feed',
        'category' => 'promotion',
        'name' => 'شحن مجاني',
        'description' => 'أعلن عن شحن مجاني لفترة محدودة.',
        'content' => "شحن مجاني على كل طلب هالأسبوع.\n\nمافي حد أدنى، ومافي كود، ومافي شروط صغيرة تحتاج تكبّر الشاشة عشان تقراها. اختر اللي تبيه وإحنا نتكفل بالتوصيل.\n\nالرابط في البايو. ينتهي يوم [day].",
        'image_count' => 1,
        'image_keywords' => ['shipping', 'package', 'delivery'],
        'slides' => null,
    ],
    [
        'slug' => 'first_order_discount_feed',
        'category' => 'promotion',
        'name' => 'خصم الطلب الأول',
        'description' => 'رحّب بالعملاء الجدد بخصم على أول طلبية.',
        'content' => "أول مرة تتسوق من {{brand_name}}؟ خذ خصم [discount]% على أول طلب لك.\n\nاستخدم كود [CODE] عند الدفع. يشتغل على أي شي في المتجر، وحتى على [bestseller name] اللي الكل يسأل عنه.\n\nالرابط في البايو.",
        'image_count' => 1,
        'image_keywords' => ['welcome', 'shop', 'discount'],
        'slides' => null,
    ],
    [
        'slug' => 'quick_how_to_tip_feed',
        'category' => 'educational',
        'name' => 'نصيحة سريعة',
        'description' => 'شارك نصيحة عملية واحدة من مجالك.',
        'content' => "هذي فكرة بسيطة تسهّل [task]: [tip in one sentence].\n\nبدأنا نسويها بعد [reason or story]. وفّرت علينا [time/money/effort] خلال أسبوع بس.\n\nاحفظ المنشور عشان ترجع له. الرابط في البايو للدليل الكامل.",
        'image_count' => 1,
        'image_keywords' => ['notebook', 'desk', 'work'],
        'slides' => null,
    ],
    [
        'slug' => 'common_mistake_feed',
        'category' => 'educational',
        'name' => 'الخطأ الشائع',
        'description' => 'سلّط الضوء على خطأ متكرر وطريقة حله.',
        'content' => "الخطأ اللي نشوفه كثير في [topic]: [the mistake].\n\nسهل الوقوع فيه. أغلب الناس ما يدرون إنه يكلفهم [consequence] لين حد ينبّههم.\n\nالحل بسيط: [the fix]. جرّبه هالأسبوع وشوف الفرق.",
        'image_count' => 1,
        'image_keywords' => ['warning', 'thinking', 'desk'],
        'slides' => null,
    ],
    [
        'slug' => 'myth_vs_truth_feed',
        'category' => 'educational',
        'name' => 'خرافة مقابل حقيقة',
        'description' => 'فنّد خرافة شائعة في مجالك.',
        'content' => "الخرافة: [common belief about your industry].\n\nالحقيقة: [the reality, with one supporting detail].\n\nإحنا كمان كنا نصدّق الخرافة. لكن تابعناها لمدة [time period] والأرقام قالت عكس ذلك. احفظ المنشور لو سمعت نفس الكلام.",
        'image_count' => 1,
        'image_keywords' => ['question', 'thinking', 'idea'],
        'slides' => null,
    ],
    [
        'slug' => 'glossary_term_feed',
        'category' => 'educational',
        'name' => 'شرح مصطلح',
        'description' => 'اشرح مصطلح واحد من مجالك بلغة بسيطة.',
        'content' => "[Term]: وش يعني فعلياً.\n\nأغلب الأدلة تشرحه بمصطلحات معقّدة أكثر. هذي النسخة المبسّطة: [one-sentence definition].\n\nمثال حقيقي من شغلنا: [short example]. احفظ المنشور لو كنت توافق بالاجتماعات وأنت ما فاهم.",
        'image_count' => 1,
        'image_keywords' => ['book', 'glossary', 'study'],
        'slides' => null,
    ],
    [
        'slug' => 'workspace_tour_feed',
        'category' => 'behind_the_scenes',
        'name' => 'جولة في مكان العمل',
        'description' => 'أرِ متابعينك المكان اللي يصير فيه الشغل.',
        'content' => "وين يصير الشغل.\n\nهذا [room/space] في {{brand_name}}. النبتة اللي في الركن نجت من ثلاث نقلات مكتب. واللوح الأبيض ما انمسح من شهر [month].\n\nمو مرتب بشكل مثالي، بس هو مكاننا.",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'desk', 'studio'],
        'slides' => null,
    ],
    [
        'slug' => 'how_its_made_feed',
        'category' => 'behind_the_scenes',
        'name' => 'كيف يُصنع',
        'description' => 'أرِ خطوة واحدة من عملية الإنتاج.',
        'content' => "هذي الخطوة [number] من طريقة صنعنا لـ [product].\n\nتاخذ تقريباً [time] وإحنا نسويها يدوياً. مافي اختصارات هنا، خصوصاً إننا جربنا الاختصار مرة وخرّب دفعة كاملة.\n\nتفاصيل أكثر عن العملية في الرابط في البايو.",
        'image_count' => 1,
        'image_keywords' => ['craft', 'making', 'workshop'],
        'slides' => null,
    ],
    [
        'slug' => 'team_member_intro_feed',
        'category' => 'behind_the_scenes',
        'name' => 'تعريف بعضو الفريق',
        'description' => 'قدّم عضو واحد من الفريق.',
        'content' => "تعرّف على [name]، [role] عندنا في {{brand_name}}.\n\n[Name] انضم لنا من [time ago] ويدير [area]. خارج الشغل، بتلقاه [hobby or interest].\n\nإذا راسلت الدعم مؤخراً، احتمال كبير إن [name] هو اللي ردّ عليك.",
        'image_count' => 1,
        'image_keywords' => ['portrait', 'team', 'person'],
        'slides' => null,
    ],
    [
        'slug' => 'a_day_in_the_life_feed',
        'category' => 'behind_the_scenes',
        'name' => 'يوم من حياتنا',
        'description' => 'استعرض يوم عادي داخل الشركة.',
        'content' => "يوم ثلاثاء عادي في {{brand_name}}.\n\nالصباح هادئ، أغلبه إيميلات واجتماع سريع واحد. بعد الظهر يصير فيه حركة أكثر لما يبدأ [activity]. وبحلول الساعة 5 عادةً حد يكون خرّب شي وحد ثاني صلّحه.\n\nهذا هو الشغل كله بصراحة.",
        'image_count' => 1,
        'image_keywords' => ['office', 'work', 'coffee'],
        'slides' => null,
    ],
    [
        'slug' => 'customer_quote_feed',
        'category' => 'testimonial',
        'name' => 'اقتباس من عميل',
        'description' => 'شارك اقتباساً مميزاً من أحد العملاء.',
        'content' => "\"[Customer quote in their own words]\"، [Customer name]، [city or role]\n\nوصلنا هذا الأسبوع الماضي وحسّينا لازم نشاركه. شكراً [first name].\n\nإذا {{brand_name}} ساعدك في [outcome]، نحب نسمع تجربتك. رد علينا أو راسلنا خاص.",
        'image_count' => 1,
        'image_keywords' => ['quote', 'happy', 'customer'],
        'slides' => null,
    ],
    [
        'slug' => 'before_after_result_feed',
        'category' => 'testimonial',
        'name' => 'قبل وبعد',
        'description' => 'سلّط الضوء على تحول حقيقي لأحد العملاء.',
        'content' => "قبل: [starting point].\nبعد: [result with a number if possible].\n\n[Customer name] تعاون معنا لمدة [time period]. التغيير ما صار بليلة وضحاها، بس تقدر تشوف وين بدأت الأمور تتغير.\n\nالرابط في البايو إذا تبي نتيجة مشابهة.",
        'image_count' => 1,
        'image_keywords' => ['transformation', 'result', 'progress'],
        'slides' => null,
    ],
    [
        'slug' => 'star_rating_review_feed',
        'category' => 'testimonial',
        'name' => 'تقييم خمس نجوم',
        'description' => 'سلّط الضوء على تقييم خمس نجوم حديث.',
        'content' => "★★★★★\n\n\"[Pulled review text, two to three sentences]\"\n\n[Reviewer first name] كتب هذا التقييم أمس. نقرأ كل تقييم يوصلنا، الطيب والقاسي.\n\nاكتب تقييمك عبر الرابط في البايو.",
        'image_count' => 1,
        'image_keywords' => ['stars', 'review', 'rating'],
        'slides' => null,
    ],
    [
        'slug' => 'case_study_snapshot_feed',
        'category' => 'testimonial',
        'name' => 'لمحة عن دراسة حالة',
        'description' => 'قدّم لمحة عن قصة نجاح أطول لأحد العملاء.',
        'content' => "كيف استخدم [customer or company] {{brand_name}} عشان يحقق [outcome].\n\nخلال [time period]، انتقلوا من [starting point] إلى [result]. التفاصيل الكاملة تغطي وش جربوا أول وايش اللي نجح أخيراً.\n\nالرابط في البايو لدراسة الحالة الكاملة.",
        'image_count' => 1,
        'image_keywords' => ['case study', 'meeting', 'results'],
        'slides' => null,
    ],
    [
        'slug' => 'one_tool_we_use_feed',
        'category' => 'industry_tip',
        'name' => 'أداة نستخدمها',
        'description' => 'رشّح أداة تستخدمها فعلياً.',
        'content' => "أداة نستخدمها كل أسبوع: [tool name].\n\nجربنا [number] بديل قبل ما نستقر على هذي. اللي قنعنا فيها كان [specific feature]، مو التسويق اللي في الصفحة الرئيسية.\n\nما هذا إعلان مدفوع. بس أداة مفيدة فعلاً.",
        'image_count' => 1,
        'image_keywords' => ['tools', 'software', 'laptop'],
        'slides' => null,
    ],
    [
        'slug' => 'industry_trend_take_feed',
        'category' => 'industry_tip',
        'name' => 'رأي في اتجاه السوق',
        'description' => 'شارك رأيك الصريح في اتجاه حالي بمجالك.',
        'content' => "الكل في [industry] يتكلم عن [trend].\n\nرأينا بصراحة: مفيد في [use case]، لكن مو مناسب لـ [other use case]. جربناه على مشروع صغير قبل ما نلتزم فيه، وهذي النسخة اللي ننصح فيها.\n\nوش كانت تجربتك؟ خبرنا في التعليقات.",
        'image_count' => 1,
        'image_keywords' => ['trend', 'industry', 'analysis'],
        'slides' => null,
    ],
    [
        'slug' => 'pricing_advice_feed',
        'category' => 'industry_tip',
        'name' => 'نصيحة في التسعير',
        'description' => 'شارك درساً في التسعير من تجربتك.',
        'content' => "الخطأ اللي وقعنا فيه بالتسعير: [the mistake].\n\nظللنا نسعّر أقل من قيمته الفعلية لمدة [period] لين حد نبّهنا إن الأرقام ما تظبط. رفعنا الأسعار [percent]، خسرنا [number] عميل، وحافظنا على الباقي، وربحنا أكثر.\n\nإذا كنت عالق بنفس المشكلة، الرابط في البايو فيه تفاصيل تسعيرنا كاملة.",
        'image_count' => 1,
        'image_keywords' => ['money', 'price', 'calculator'],
        'slides' => null,
    ],
    [
        'slug' => 'workflow_tip_feed',
        'category' => 'industry_tip',
        'name' => 'نصيحة في سير العمل',
        'description' => 'شارك تحسيناً بسيطاً في سير العمل.',
        'content' => "تغيير بسيط في سير العمل وفّر علينا ساعات: [the change].\n\nقبل، [old way]. بعد، [new way]. أخذنا تقريباً أسبوع نتعود عليه وما رجعنا للطريقة القديمة.\n\nإذا جربته، خبرنا كيف كانت النتيجة.",
        'image_count' => 1,
        'image_keywords' => ['workflow', 'productivity', 'planner'],
        'slides' => null,
    ],
    [
        'slug' => 'event_announcement_feed',
        'category' => 'event',
        'name' => 'إعلان فعالية',
        'description' => 'أعلن عن فعالية قادمة.',
        'content' => "احجز الموعد من الحين.\n\n{{brand_name}} تستضيف [event name] بتاريخ [date] في [location or online].\n\nراح يكون فيه [speakers, format, or what to expect]. المقاعد محدودة بـ [number] هالمرة.\n\nأكّد حضورك عبر الرابط في البايو.",
        'image_count' => 1,
        'image_keywords' => ['event', 'invitation', 'calendar'],
        'slides' => null,
    ],
    [
        'slug' => 'webinar_invite_feed',
        'category' => 'event',
        'name' => 'دعوة لندوة إلكترونية',
        'description' => 'روّج لندوة إلكترونية قادمة.',
        'content' => "ندوة إلكترونية مجانية: [topic]. بتاريخ [date] الساعة [time].\n\n[Host name] راح يستعرض [main points] وبعدين يفتح المجال للأسئلة المباشرة آخر [minutes].\n\nإذا ما تقدر تحضر، سجّل برضو وبنرسل لك التسجيل.\n\nالرابط في البايو.",
        'image_count' => 1,
        'image_keywords' => ['webinar', 'laptop', 'presentation'],
        'slides' => null,
    ],
    [
        'slug' => 'meetup_recap_feed',
        'category' => 'event',
        'name' => 'ملخص لقاء',
        'description' => 'لخّص فعالية حضورية حديثة.',
        'content' => "[Number] شخص، [city]، وقاعة وحدة.\n\nلقاء أمس جمع ناس شغّالين في [field]. أحلى نقاش في الليلة كان عن [topic]، بدأ على فنجان قهوة وما انتهى فعلياً.\n\nشكراً لكل من حضر. اللقاء الجاي بتاريخ [date].",
        'image_count' => 1,
        'image_keywords' => ['meetup', 'crowd', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'live_stream_reminder_feed',
        'category' => 'event',
        'name' => 'تذكير ببث مباشر',
        'description' => 'ذكّر متابعينك ببث مباشر قادم.',
        'content' => "بنبث مباشر يوم [day] الساعة [time].\n\nراح نتكلم عن [topic]. بدون نص محفوظ، بس أسئلة وأي شي يجينا من الشات.\n\nفعّل الإشعارات عشان ما يفوتك. أو لا، التسجيل بيكون متاح على الحساب بعدين.",
        'image_count' => 1,
        'image_keywords' => ['live', 'broadcast', 'camera'],
        'slides' => null,
    ],
    [
        'slug' => 'this_or_that_feed',
        'category' => 'engagement',
        'name' => 'هذا أو ذاك',
        'description' => 'اطرح سؤال اختيار بسيط بين خيارين.',
        'content' => "[Option A] ولا [Option B]؟\n\nنتناقش في هذا الموضوع بالمكتب مرة واحدة على الأقل كل أسبوع. فضوليين نعرف مين بيفوز هنا.\n\nصوّت في التعليقات. مافي إجابة غلط، بس أكيد فيه وحدة صح.",
        'image_count' => 1,
        'image_keywords' => ['choice', 'options', 'vote'],
        'slides' => null,
    ],
    [
        'slug' => 'fill_in_the_blank_feed',
        'category' => 'engagement',
        'name' => 'أكمل الفراغ',
        'description' => 'حفّز متابعينك بسؤال إكمال فراغ.',
        'content' => "أكمل الجملة: \"أول شي أسويه كل صباح هو ___.\"\n\nسألنا الفريق وطلعت إجابات من \"أتفقد Slack\" لين \"أتجنب فتح Slack.\" فضوليين نعرف إجابتك.\n\nاكتبها في التعليقات.",
        'image_count' => 1,
        'image_keywords' => ['question', 'morning', 'coffee'],
        'slides' => null,
    ],
    [
        'slug' => 'comment_question_feed',
        'category' => 'engagement',
        'name' => 'سؤال للتفاعل',
        'description' => 'اطرح سؤالاً مفتوحاً يحفّز التعليقات.',
        'content' => "سؤال للجميع: وش أفضل [topic-related thing] جربته هالسنة؟\n\nنجمع قائمة ونبي اختيارات حقيقية، مو نفس الخمسة اللي الكل يذكرهم.\n\nاكتب اختيارك تحت. بنشارك الأفضل الأسبوع الجاي.",
        'image_count' => 1,
        'image_keywords' => ['conversation', 'community', 'chat'],
        'slides' => null,
    ],
    [
        'slug' => 'tag_a_friend_feed',
        'category' => 'engagement',
        'name' => 'أشِر لصديق',
        'description' => 'شجّع على الإشارة لصديق بموقف يشبه الجميع.',
        'content' => "أشِر للصديق اللي [relatable scenario].\n\nكلنا نعرف وحد كذا. يمكن أنت هو. على كل حال، هذا المنشور له.\n\nنقطة إضافية إذا رجع أشار لك.",
        'image_count' => 1,
        'image_keywords' => ['friends', 'people', 'fun'],
        'slides' => null,
    ],
];
