<?php

declare(strict_types=1);

return [
    [
        'slug' => 'feature_launch_carousel',
        'category' => 'product_launch',
        'name' => 'إطلاق ميزة جديدة',
        'description' => 'أعلن عن ميزة جديدة في منتجك بقصة من 5 شرائح.',
        'content' => '{{brand_name}} أطلقنا شي نتحمّس له. مرّر عشان تشوف الجديد.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'الجديد', 'body' => 'نظرة سريعة على آخر تحديث.', 'image_keywords' => ['product', 'launch']],
            ['title' => 'كيف تشتغل', 'body' => 'ثلاث خطوات وتكون جاهز.', 'image_keywords' => ['workflow']],
            ['title' => 'ليش تهمك', 'body' => 'أسرع، أبسط، ضغطات أقل.', 'image_keywords' => ['speed']],
            ['title' => 'لمين هذي', 'body' => 'مصممة للفرق اللي تنجز.', 'image_keywords' => ['team']],
            ['title' => 'جربها الحين', 'body' => 'متوفرة اليوم. الرابط في البايو.', 'image_keywords' => ['phone', 'app']],
        ],
    ],
    [
        'slug' => 'five_tips_carousel',
        'category' => 'educational',
        'name' => 'كاروسيل 5 نصائح',
        'description' => 'شارك خمس نصائح عملية بكاروسيل قابل للتمرير.',
        'content' => '5 أشياء ودّي أعرفها عن [الموضوع] بدري. احفظ المنشور لين وقت الحاجة. 👇',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'نصيحة #1', 'body' => '[النصيحة الأولى، خلها محددة وقابلة للتطبيق.]', 'image_keywords' => ['idea', 'lightbulb']],
            ['title' => 'نصيحة #2', 'body' => '[النصيحة الثانية، استخدم مثال واقعي إذا قدرت.]', 'image_keywords' => ['notebook']],
            ['title' => 'نصيحة #3', 'body' => '[النصيحة الثالثة، خلها قصيرة.]', 'image_keywords' => ['focus']],
            ['title' => 'نصيحة #4', 'body' => '[النصيحة الرابعة، شي مفاجئ أو عكس المتوقع.]', 'image_keywords' => ['surprise']],
            ['title' => 'نصيحة #5', 'body' => '[النصيحة الخامسة، اختم بقوة بفكرة تتذكرها.]', 'image_keywords' => ['success']],
        ],
    ],
    [
        'slug' => 'process_reveal_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'كشف خطوات العمل',
        'description' => 'خذ متابعينك في جولة على طريقة صنع منتجك أو خدمتك.',
        'content' => 'تساءلت يومًا كيف نصنع [المنتج/الخدمة]؟ مرّر عشان تشوف كل خطوة. ✨',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'يبدأ بالبحث', 'body' => 'كل مشروع يبدأ بفهم المشكلة بعمق.', 'image_keywords' => ['research', 'desk']],
            ['title' => 'التصميم والتطوير', 'body' => 'نبني نماذج أولية بسرعة ونختبرها باستمرار.', 'image_keywords' => ['design', 'sketch']],
            ['title' => 'صناعة المنتج الفعلي', 'body' => 'حرفية ودقة في كل تفصيلة.', 'image_keywords' => ['craft', 'build']],
            ['title' => 'النتيجة النهائية', 'body' => 'جودة تحسّها من أول استخدام.', 'image_keywords' => ['product', 'final']],
        ],
    ],
    [
        'slug' => 'quick_stat_carousel',
        'category' => 'industry_tip',
        'name' => 'كاروسيل إحصائيات سريع',
        'description' => 'اعرض إحصائيات القطاع بصيغة كاروسيل مرئي.',
        'content' => 'أرقام [القطاع] اللي لازم تكون في بال كل مسوّق هالسنة. 📊',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'إحصائية #1', 'body' => '[X]% من [الجمهور] يقولون [النتيجة]. المصدر: [المصدر]', 'image_keywords' => ['chart', 'data']],
            ['title' => 'إحصائية #2', 'body' => 'زيادة [Y]% في [المقياس] سنة بعد سنة.', 'image_keywords' => ['growth', 'graph']],
            ['title' => 'إحصائية #3', 'body' => 'بحلول [السنة]، [التوقع].', 'image_keywords' => ['future', 'trend']],
            ['title' => 'وش يعني هذا لك', 'body' => '[فكرة عملية مبنية على الإحصائيات أعلاه.]', 'image_keywords' => ['action', 'plan']],
        ],
    ],
    [
        'slug' => 'event_recap_carousel',
        'category' => 'event',
        'name' => 'ملخص فعالية',
        'description' => 'لخّص أبرز لحظات فعالية أو مؤتمر أخير.',
        'content' => 'خلصنا للتو من [اسم الفعالية] وكانت رهيبة. هذي أبرز اللحظات. 🙌',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'بدأ كل شي بـ...', 'body' => '[لحظة الافتتاح أو أبرز الكلمة الرئيسية.]', 'image_keywords' => ['conference', 'stage']],
            ['title' => 'الجلسة اللي صار الكل يتكلم عنها', 'body' => '[أبرز فكرة من الجلسة المميزة.]', 'image_keywords' => ['presentation', 'crowd']],
            ['title' => 'التواصل مع المجتمع', 'body' => '[أبرز لحظات التواصل أو الحضور.]', 'image_keywords' => ['networking', 'people']],
            ['title' => 'نشوفكم المرة الجاية', 'body' => 'تابع {{brand_name}} عشان توصلك تحديثات فعاليتنا الجاية.', 'image_keywords' => ['celebration']],
        ],
    ],
    [
        'slug' => 'product_lineup_carousel',
        'category' => 'product_launch',
        'name' => 'كشف تشكيلة المنتجات',
        'description' => 'اكشف عن تشكيلة المنتجات كاملة، منتج واحد في كل شريحة.',
        'content' => 'صنعنا [العدد] أشياء جديدة. هذي التشكيلة كاملة من {{brand_name}}.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'تعرّف على التشكيلة', 'body' => '[العدد] قطع جديدة، صُممت مع بعض. كل وحدة تحل مشكلة معينة.', 'image_keywords' => ['products', 'lineup']],
            ['title' => 'القطعة الأولى', 'body' => '[اسم المنتج 1]. الأفضل لـ [حالة الاستخدام].', 'image_keywords' => ['product', 'studio']],
            ['title' => 'القطعة الثانية', 'body' => '[اسم المنتج 2]. يتناسق مع القطعة الأولى إذا تبي [الفائدة].', 'image_keywords' => ['object', 'detail']],
            ['title' => 'القطعة الثالثة', 'body' => '[اسم المنتج 3]. القطعة اللي ما وقفنا نطورها إلى أن حسّينا إنها مضبوطة.', 'image_keywords' => ['craft', 'closeup']],
            ['title' => 'تسوّق الإصدار', 'body' => 'متوفرة بتاريخ [التاريخ]. الرابط في البايو.', 'image_keywords' => ['shop', 'phone']],
        ],
    ],
    [
        'slug' => 'before_after_launch_carousel',
        'category' => 'product_launch',
        'name' => 'قبل وبعد الإطلاق',
        'description' => 'اعرض التطور من النسخة القديمة للنسخة الجديدة.',
        'content' => 'نفس الفكرة، بس معاد بناؤها. هذا اللي تغيّر في [المنتج] الجديد من {{brand_name}}.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'قبل', 'body' => '[النسخة القديمة. وين كانت زينة، ووين قصّرت.]', 'image_keywords' => ['old', 'product']],
            ['title' => 'بعد', 'body' => '[النسخة الجديدة. جملة وحدة عن أكبر تغيير.]', 'image_keywords' => ['new', 'product']],
            ['title' => 'وش صلّحنا', 'body' => '[مشكلة محددة أخبرنا فيها العملاء، وكيف عالجناها.]', 'image_keywords' => ['detail', 'redesign']],
            ['title' => 'متوفر الحين', 'body' => 'تلقاه في المتجر. الرابط في البايو.', 'image_keywords' => ['store', 'phone']],
        ],
    ],
    [
        'slug' => 'spec_breakdown_carousel',
        'category' => 'product_launch',
        'name' => 'كاروسيل تفاصيل المواصفات',
        'description' => 'فصّل مواصفات المنتج على عدة شرائح.',
        'content' => 'ورقة المواصفات كاملة لـ [المنتج]. كل اللي بداخله بتمريرة وحدة.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'تعرّف على [المنتج]', 'body' => 'مصمم لـ [حالة الاستخدام]. متوفر بتاريخ [التاريخ].', 'image_keywords' => ['product', 'reveal']],
            ['title' => 'الخامات', 'body' => '[تفاصيل الخامة. من وين مصدرها. وليش تهم في الإحساس النهائي.]', 'image_keywords' => ['materials', 'texture']],
            ['title' => 'الأبعاد', 'body' => '[المقاس، الوزن، ملاحظات المقاس. أرقام فعلاً يبيها الناس قبل الشراء.]', 'image_keywords' => ['measurement', 'detail']],
            ['title' => 'الأداء', 'body' => '[رقم الأداء الأساسي. عمر البطارية، مدة التشغيل، قوة التحمل، أي شي يناسب.]', 'image_keywords' => ['performance', 'test']],
            ['title' => 'محتويات العلبة', 'body' => '[قائمة المحتويات: المنتج، الملحقات، الدليل، وغيرها.]', 'image_keywords' => ['unboxing', 'box']],
            ['title' => 'اطلب نسختك', 'body' => 'الرابط في البايو. الشحن خلال [المدة].', 'image_keywords' => ['shipping', 'parcel']],
        ],
    ],
    [
        'slug' => 'flash_sale_carousel',
        'category' => 'promotion',
        'name' => 'تخفيضات خاطفة',
        'description' => 'روّج لتخفيضات محدودة المدة عبر شرائح.',
        'content' => 'خصم [النسبة]% لمدة [الساعات] ساعة القادمة في {{brand_name}}. اقرأ كل شريحة عشان ما يفوتك شي.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'التخفيضات الخاطفة بدأت', 'body' => 'خصم [النسبة]% لين [تاريخ ووقت الانتهاء]. بدون كود.', 'image_keywords' => ['sale', 'tag']],
            ['title' => 'وش يشمل العرض', 'body' => '[الفئات المشمولة بالتخفيض، والمستثناة إن وجدت. كن واضح بما لا يشمله العرض.]', 'image_keywords' => ['products', 'shop']],
            ['title' => 'الأكثر طلبًا', 'body' => '[منتجين أو ثلاثة من الأكثر مبيعًا اللي الناس تخطفها أول ما تبدأ التخفيضات.]', 'image_keywords' => ['favorites', 'shelf']],
            ['title' => 'تسوّق قبل الانتهاء', 'body' => 'الرابط في البايو. لما تخلص الكمية تخلص.', 'image_keywords' => ['phone', 'cart']],
        ],
    ],
    [
        'slug' => 'bundle_deal_carousel',
        'category' => 'promotion',
        'name' => 'كاروسيل عرض الباقة',
        'description' => 'اشرح عرض الباقة شريحة بشريحة.',
        'content' => 'ثلاث قطع، سعر واحد. وفّر [المبلغ] لما تشتريهم مع بعض من {{brand_name}}.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'الباقة', 'body' => '[وصف مختصر لمحتويات الباقة وإجمالي التوفير.]', 'image_keywords' => ['bundle', 'box']],
            ['title' => 'القطعة الأولى', 'body' => '[أول قطعة في الباقة ووظيفتها لحالها.]', 'image_keywords' => ['product', 'one']],
            ['title' => 'القطعة الثانية', 'body' => '[القطعة الثانية وليش تتناسق مع الأولى.]', 'image_keywords' => ['product', 'two']],
            ['title' => 'القطعة الثالثة', 'body' => '[القطعة الثالثة. اللي تربط الباقة مع بعض.]', 'image_keywords' => ['product', 'three']],
            ['title' => 'اقتنِ الباقة', 'body' => 'وفّر [المبلغ]. متوفرة إلى نفاد الكمية.', 'image_keywords' => ['bag', 'shopping']],
        ],
    ],
    [
        'slug' => 'first_order_discount_carousel',
        'category' => 'promotion',
        'name' => 'خصم أول طلب',
        'description' => 'رحّب بالعملاء الجدد بخصم على أول طلب.',
        'content' => 'جديد عندنا؟ استخدم كود [الكود] وخذ خصم [النسبة]% على أول طلب من {{brand_name}}.',
        'image_count' => 3,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'عرض الترحيب', 'body' => 'خصم [النسبة]% على أول طلب. الكود: [الكود]. صالح لمدة [المدة].', 'image_keywords' => ['welcome', 'gift']],
            ['title' => 'وش يبدأ فيه الناس', 'body' => '[منتج أو اثنين نقطة بداية زينة للعملاء الجدد.]', 'image_keywords' => ['bestseller', 'product']],
            ['title' => 'كيف تستخدمه', 'body' => 'أضف للسلة، الصق كود [الكود] عند الدفع. الرابط في البايو.', 'image_keywords' => ['checkout', 'phone']],
        ],
    ],
    [
        'slug' => 'free_shipping_carousel',
        'category' => 'promotion',
        'name' => 'شحن مجاني نهاية الأسبوع',
        'description' => 'روّج لفترة شحن مجاني محدودة.',
        'content' => 'شحن مجاني في {{brand_name}} نهاية هالأسبوع بس. بدون حد أدنى.',
        'image_count' => 3,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'نهاية أسبوع الشحن المجاني', 'body' => 'من [الجمعة] إلى [الأحد]. بدون كود، وبدون حد أدنى للطلب.', 'image_keywords' => ['shipping', 'box']],
            ['title' => 'وين نوصّل', 'body' => '[المناطق أو الدول المشمولة. وضّح أي استثناءات بشكل واضح.]', 'image_keywords' => ['map', 'globe']],
            ['title' => 'تسوّق في نهاية الأسبوع', 'body' => 'اضغط الرابط في البايو قبل منتصف ليلة [الأحد] بتوقيت [المنطقة الزمنية].', 'image_keywords' => ['cart', 'phone']],
        ],
    ],
    [
        'slug' => 'beginner_guide_carousel',
        'category' => 'educational',
        'name' => 'كاروسيل دليل المبتدئين',
        'description' => 'علّم موضوعًا من الصفر لأول نتيجة قابلة للتطبيق.',
        'content' => '[الموضوع] للمبتدئين تمامًا. احفظ المنشور لين وقت الحاجة. 👇',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'ابدأ من هنا', 'body' => 'إذا [الموضوع] يحسّسك إنه صعب، هذي النسخة اللي ساعدتني لما كنت جديد.', 'image_keywords' => ['beginner', 'notes']],
            ['title' => 'وش هو فعليًا', 'body' => '[تعريف بسيط. تجنّب المصطلحات المعقدة. جملة وحدة كافية.]', 'image_keywords' => ['concept', 'sketch']],
            ['title' => 'ليش الناس تهتم', 'body' => '[السبب الملموس اللي يخلي المبتدئ يهتم بتعلّم هذا.]', 'image_keywords' => ['question', 'curious']],
            ['title' => 'أول شي تجربه', 'body' => '[خطوة صغيرة ومحددة يقدر يسويها في أقل من 10 دقايق.]', 'image_keywords' => ['hands', 'desk']],
            ['title' => 'غلطة شائعة', 'body' => '[الفخ اللي يقع فيه أغلب المبتدئين. كن محدد.]', 'image_keywords' => ['mistake', 'fix']],
            ['title' => 'وش الخطوة الجاية', 'body' => '[كتاب، قناة، أو مصدر من {{brand_name}} للخطوة الجاية.]', 'image_keywords' => ['library', 'resource']],
        ],
    ],
    [
        'slug' => 'common_mistakes_carousel',
        'category' => 'educational',
        'name' => 'أخطاء شائعة',
        'description' => 'سلّط الضوء على أخطاء شائعة وكيف تصلحها.',
        'content' => '5 أخطاء أشوفها باستمرار في [الموضوع]. الغلطة رقم 3 تعلّمتها بالطريقة الصعبة.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'الأخطاء', 'body' => 'خمسة أشياء يغلط فيها الناس في [الموضوع]، والصح بدالها.', 'image_keywords' => ['mistake', 'pen']],
            ['title' => 'الغلطة 1', 'body' => '[الغلطة الأولى. والحل في جملة وحدة.]', 'image_keywords' => ['error', 'paper']],
            ['title' => 'الغلطة 2', 'body' => '[الغلطة الثانية والحل.]', 'image_keywords' => ['confused', 'desk']],
            ['title' => 'الغلطة 3', 'body' => '[الغلطة الثالثة. اللي تفاجئ الناس.]', 'image_keywords' => ['surprised', 'thought']],
            ['title' => 'الغلطة 4', 'body' => '[الغلطة الرابعة والحل.]', 'image_keywords' => ['process', 'workspace']],
            ['title' => 'الغلطة 5', 'body' => '[الغلطة الأخيرة. اختم بالبديل الصح.]', 'image_keywords' => ['solution', 'check']],
        ],
    ],
    [
        'slug' => 'glossary_carousel',
        'category' => 'educational',
        'name' => 'كاروسيل المصطلحات',
        'description' => 'عرّف خمسة مصطلحات من مجالك بلغة بسيطة.',
        'content' => '5 مصطلحات في [القطاع] بشرح بسيط بدون تعقيد. احفظ المنشور لين وقت الحاجة.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'المصطلحات، مفكوكة', 'body' => 'خمس كلمات في [القطاع] الناس تستخدمها وكأن الكل يعرف معناها.', 'image_keywords' => ['dictionary', 'book']],
            ['title' => '[المصطلح 1]', 'body' => '[تعريف بسيط. جملة مثال واحدة.]', 'image_keywords' => ['letters', 'text']],
            ['title' => '[المصطلح 2]', 'body' => '[تعريف بسيط. جملة مثال واحدة.]', 'image_keywords' => ['letters', 'paper']],
            ['title' => '[المصطلح 3]', 'body' => '[تعريف بسيط. جملة مثال واحدة.]', 'image_keywords' => ['note', 'pen']],
            ['title' => '[المصطلح 4]', 'body' => '[تعريف بسيط. جملة مثال واحدة.]', 'image_keywords' => ['definition', 'page']],
            ['title' => '[المصطلح 5]', 'body' => '[تعريف بسيط. جملة مثال واحدة.]', 'image_keywords' => ['glossary', 'open book']],
        ],
    ],
    [
        'slug' => 'step_by_step_tutorial_carousel',
        'category' => 'educational',
        'name' => 'درس تعليمي خطوة بخطوة',
        'description' => 'اشرح طريقة بسيطة بخطوات واضحة.',
        'content' => 'كيف تسوي [المهمة] في [العدد] خطوات. احفظ المنشور عشان يكون عندك المرة الجاية.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'وش تحتاجه', 'body' => '[اذكر الأدوات أو المستلزمات. خلها مختصرة.]', 'image_keywords' => ['tools', 'supplies']],
            ['title' => 'خطوة 1', 'body' => '[الخطوة الأولى. إجراء محدد، مو هدف عام.]', 'image_keywords' => ['hands', 'work']],
            ['title' => 'خطوة 2', 'body' => '[الخطوة الثانية. كيف يفترض يكون شكل النتيجة قبل ما تكمل.]', 'image_keywords' => ['progress', 'desk']],
            ['title' => 'خطوة 3', 'body' => '[الخطوة الثالثة. اذكر أشيع غلطة تصير هنا.]', 'image_keywords' => ['focus', 'detail']],
            ['title' => 'خلصنا', 'body' => '[كيف يفترض تكون النتيجة النهائية. فكرة صورة وحدة.]', 'image_keywords' => ['finished', 'result']],
        ],
    ],
    [
        'slug' => 'team_intro_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'تعرّف على الفريق',
        'description' => 'قدّم أعضاء الفريق شريحة شريحة.',
        'content' => 'الوجوه اللي وراء {{brand_name}}. مرر لتتعرف على الفريق اللي يسوي الشغل.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'الفريق', 'body' => 'احنا [number] أشخاص موزعين على [locations]. وهذا اللي يسويه كل واحد فيهم.', 'image_keywords' => ['team', 'office']],
            ['title' => '[الاسم 1]', 'body' => '[الدور. شي يتكفل فيه وشي يحبه بعيد عن الشغل.]', 'image_keywords' => ['portrait', 'work']],
            ['title' => '[الاسم 2]', 'body' => '[الدور. تفصيلة توضح شخصيته، مو بس مسماه الوظيفي.]', 'image_keywords' => ['portrait', 'desk']],
            ['title' => '[الاسم 3]', 'body' => '[الدور. شي محدد سواه هالشهر.]', 'image_keywords' => ['portrait', 'studio']],
            ['title' => 'سلّم علينا', 'body' => 'الخاص مفتوح، ونرد عليه بأنفسنا.', 'image_keywords' => ['phone', 'chat']],
        ],
    ],
    [
        'slug' => 'workspace_tour_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'جولة في مكان العمل',
        'description' => 'خذ الجمهور بجولة في الاستوديو أو المطبخ أو المكتب عبر الشرائح.',
        'content' => 'جولة في المكان اللي يتكوّن فيه {{brand_name}} فعليًا. أبسط بكثير مما تتخيل.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'وين يصير الشغل', 'body' => '[الموقع، المساحة، ونوع المكان بجملة وحدة.]', 'image_keywords' => ['studio', 'workshop']],
            ['title' => 'طاولة الشغل', 'body' => '[اللي يكون فوق الطاولة أو المكتب في أغلب الأيام.]', 'image_keywords' => ['workbench', 'tools']],
            ['title' => 'الركن اللي ما أحد يشوفه', 'body' => '[تفصيلة صادقة: رف فوضوي، جدار ملاحظات لاصقة، أو ركن القهوة.]', 'image_keywords' => ['corner', 'mess']],
            ['title' => 'المكان المفضّل', 'body' => '[الكرسي، الشباك، أو الإضاءة اللي تحسّن اليوم.]', 'image_keywords' => ['light', 'window']],
            ['title' => 'ترقّبوا المزيد', 'body' => 'في لمحات جاية. تابع {{brand_name}} عشان توصلك.', 'image_keywords' => ['camera', 'door']],
        ],
    ],
    [
        'slug' => 'a_day_in_the_life_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'يوم من حياتنا',
        'description' => 'اعرض يوم عمل كامل من الصبح للمسا.',
        'content' => 'يوم حقيقي في {{brand_name}}، ساعة بساعة. مو نسخة اللقطات المنتقاة.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => '٧:٣٠ صباحًا', 'body' => '[كيف يبدأ اليوم فعليًا. قهوة، مشي، صندوق الوارد، أيًا كان.]', 'image_keywords' => ['morning', 'coffee']],
            ['title' => '٩:٠٠ صباحًا', 'body' => '[أول شي في جدول الشغل. كن محددًا بما يُنجز.]', 'image_keywords' => ['desk', 'laptop']],
            ['title' => '١٢:٣٠ ظهرًا', 'body' => '[الغدا. وين، مع من، أو لحاله مع بودكاست.]', 'image_keywords' => ['lunch', 'food']],
            ['title' => '٢:٠٠ عصرًا', 'body' => '[فترة العصر. الشي اللي يأخذ أكبر تركيز في ذاك اليوم.]', 'image_keywords' => ['focus', 'work']],
            ['title' => '٥:٣٠ مساءً', 'body' => '[ختام اليوم. آخر مهمة تكون عادةً قبل الانتهاء.]', 'image_keywords' => ['evening', 'office']],
            ['title' => 'بعد الدوام', 'body' => '[كيف ينتهي اليوم. جري، عشا، وقت مع الأطفال، قراءة، أي شي صحيح.]', 'image_keywords' => ['sunset', 'home']],
        ],
    ],
    [
        'slug' => 'mistakes_we_made_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'أخطاء سويناها',
        'description' => 'شارك ثلاث أخطاء حقيقية وإيش تعلمت منها.',
        'content' => '٣ أشياء غلطنا فيها هالسنة في {{brand_name}}. نشاركها لأن إخفاءها بيكون غريب.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'ليش ننشر هذا', 'body' => 'الانتصارات تاخذ اهتمام كثير، لكن الدروس الحقيقية غالبًا تكون في الأخطاء.', 'image_keywords' => ['notebook', 'writing']],
            ['title' => 'الخطأ الأول', 'body' => '[إيش جربنا. ليش ما نجح. وإيش سوينا بعدها.]', 'image_keywords' => ['error', 'desk']],
            ['title' => 'الخطأ الثاني', 'body' => '[الخطأ الثاني. كن صريحًا بالتكلفة، سواء مال أو وقت.]', 'image_keywords' => ['budget', 'paper']],
            ['title' => 'الخطأ الثالث + إيش الجاي', 'body' => '[الخطأ الثالث وشي واحد رح يتغير بسببه.]', 'image_keywords' => ['plan', 'reset']],
        ],
    ],
    [
        'slug' => 'customer_story_carousel',
        'category' => 'testimonial',
        'name' => 'قصة عميل',
        'description' => 'احكِ قصة عميل واحد عبر الشرائح.',
        'content' => 'قصة من أحد عملاء {{brand_name}}. نُشرت بإذنه.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'تعرّف على [الاسم]', 'body' => '[الاسم، شغله، ومكانه. جملتين قصيرتين.]', 'image_keywords' => ['portrait', 'person']],
            ['title' => 'المشكلة', 'body' => '[الوضع قبل استخدامه لـ {{brand_name}}. محدد، مو عام.]', 'image_keywords' => ['problem', 'thinking']],
            ['title' => 'إيش جرّب', 'body' => '[كيف لقى {{brand_name}} وكيف كانت أول تجربة له.]', 'image_keywords' => ['discover', 'try']],
            ['title' => 'إيش تغيّر', 'body' => '[النتيجة. رقم إذا متوفر، أو قصة إذا ما فيه رقم.]', 'image_keywords' => ['result', 'change']],
            ['title' => 'بكلماته', 'body' => '"[اقتباس مباشر من العميل. قصير وصادق.]"', 'image_keywords' => ['quote', 'speech']],
        ],
    ],
    [
        'slug' => 'three_reviews_carousel',
        'category' => 'testimonial',
        'name' => 'كاروسيل ثلاث تقييمات',
        'description' => 'اجمع ثلاث تقييمات حقيقية في منشور قابل للتمرير.',
        'content' => 'ثلاث تقييمات من عملاء حقيقيين هالشهر في {{brand_name}}.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'إيش يقولون الناس', 'body' => 'ثلاث اقتباسات بدون تعديل من هالشهر. الأسماء الكاملة محجوبة عند الطلب.', 'image_keywords' => ['stars', 'review']],
            ['title' => 'التقييم الأول', 'body' => '"[اقتباس مباشر من العميل.]"، [الاسم الأول، الموقع]', 'image_keywords' => ['speech', 'quote']],
            ['title' => 'التقييم الثاني', 'body' => '"[اقتباس مباشر من العميل.]"، [الاسم الأول، الموقع]', 'image_keywords' => ['feedback', 'note']],
            ['title' => 'التقييم الثالث', 'body' => '"[اقتباس مباشر من العميل.]"، [الاسم الأول، الموقع]', 'image_keywords' => ['testimonial', 'paper']],
        ],
    ],
    [
        'slug' => 'before_after_results_carousel',
        'category' => 'testimonial',
        'name' => 'نتائج قبل وبعد',
        'description' => 'اعرض نتيجة عميل بشرائح قبل وبعد.',
        'content' => 'نتيجة حقيقية لعميل استخدم [product/service] في {{brand_name}}. نفس الشخص، بفارق [time period].',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'نقطة البداية', 'body' => '[وين كان لما بدأ. النسخة الصادقة، مو المزينة.]', 'image_keywords' => ['before', 'start']],
            ['title' => 'إيش سوّى', 'body' => '[إيش استخدم وكم مرة. كن محددًا بالروتين.]', 'image_keywords' => ['process', 'routine']],
            ['title' => 'النتيجة', 'body' => '[وين هو الحين. أرقام إذا تناسب، أو صورة إذا مرئية.]', 'image_keywords' => ['after', 'result']],
            ['title' => 'بكلماته', 'body' => '"[اقتباس قصير عن أكثر شي فاجأه.]"', 'image_keywords' => ['quote', 'smile']],
        ],
    ],
    [
        'slug' => 'industry_myth_busting_carousel',
        'category' => 'industry_tip',
        'name' => 'تفنيد خرافات القطاع',
        'description' => 'فنّد ثلاث خرافات عن مجال عملك.',
        'content' => '٣ أشياء لسا الناس يصدقونها عن [industry] وهي مو صحيحة.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'خرافات نكشفها', 'body' => 'ثلاث معتقدات عن [industry] تتكرر بكل مكان وما زالت غير دقيقة.', 'image_keywords' => ['question', 'thinking']],
            ['title' => 'الخرافة الأولى', 'body' => 'الخرافة: [الاعتقاد الشائع]. الحقيقة: [الواقع الفعلي، مع تفصيلة واحدة].', 'image_keywords' => ['truth', 'note']],
            ['title' => 'الخرافة الثانية', 'body' => 'الخرافة: [الاعتقاد الشائع]. الحقيقة: [التصحيح بجملة وحدة].', 'image_keywords' => ['fact', 'paper']],
            ['title' => 'الخرافة الثالثة', 'body' => 'الخرافة: [الاعتقاد الشائع]. الحقيقة: [التصحيح]. السبب تلقاه في التعليقات.', 'image_keywords' => ['comment', 'phone']],
        ],
    ],
    [
        'slug' => 'industry_trend_carousel',
        'category' => 'industry_tip',
        'name' => 'كاروسيل اتجاهات القطاع',
        'description' => 'استعرض اتجاهًا يشكّل ملامح القطاع هالسنة.',
        'content' => 'إيش اللي يتحرك فعليًا في [industry] هالسنة، بلغة واضحة وبسيطة.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'الاتجاه', 'body' => '[سمّ الاتجاه بكلمات بسيطة. جملة وحدة توضح إيش هو.]', 'image_keywords' => ['trend', 'graph']],
            ['title' => 'ليش الحين', 'body' => '[السبب المحدد. نظام جديد، تحول تقني، أو تغيّر في السلوك.]', 'image_keywords' => ['cause', 'news']],
            ['title' => 'من يتأثر أولًا', 'body' => '[الجمهور أو نوع الشركات اللي يحس فيه قبل الجميع.]', 'image_keywords' => ['audience', 'people']],
            ['title' => 'إيش تسوي', 'body' => '[شي عملي واحد تجربه هالربع، مو مبدأ عام غامض.]', 'image_keywords' => ['action', 'plan']],
            ['title' => 'رقم واحد راقبه', 'body' => '[مقياس محدد، مع مصدره.]', 'image_keywords' => ['metric', 'data']],
        ],
    ],
    [
        'slug' => 'pro_tip_carousel',
        'category' => 'industry_tip',
        'name' => 'كاروسيل نصيحة احترافية',
        'description' => 'شارك نصيحة احترافية واحدة بعمق مع سياقها وخطواتها.',
        'content' => 'شي واحد كنت بقوله لنفسي وأنا أصغر عن [topic]. احفظ المنشور إذا فادك.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'النصيحة', 'body' => '[النسخة بجملة وحدة. قصيرة بما يكفي عشان تتذكرها.]', 'image_keywords' => ['tip', 'note']],
            ['title' => 'ليش تنجح', 'body' => '[السبب. استخدم مثال بسيط، مو ادعاء كبير.]', 'image_keywords' => ['idea', 'thought']],
            ['title' => 'كيف تطبقها', 'body' => '[الخطوات. ثلاث كحد أقصى. محددة.]', 'image_keywords' => ['steps', 'list']],
            ['title' => 'شي واحد تتجنبه', 'body' => '[الخطأ اللي يسويه الناس عند تطبيق هالنصيحة.]', 'image_keywords' => ['warning', 'caution']],
        ],
    ],
    [
        'slug' => 'event_announcement_carousel',
        'category' => 'event',
        'name' => 'إعلان فعالية',
        'description' => 'أعلن عن فعالية قادمة مع أهم التفاصيل.',
        'content' => 'رح نستضيف [Event Name] بتاريخ [date]. كل اللي تحتاج تعرفه موجود بالشرائح.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => '[اسم الفعالية]', 'body' => '[التاريخ، الموقع أو أونلاين، والفئة المستهدفة بسطر وحد.]', 'image_keywords' => ['event', 'invite']],
            ['title' => 'إيش المخطط له', 'body' => '[الأجندة بنقاط بسيطة، مو بلغة تسويقية.]', 'image_keywords' => ['agenda', 'schedule']],
            ['title' => 'من المتحدثون', 'body' => '[الأسماء ونبذة بسطر وحد. لا تتجاوز ثلاثة.]', 'image_keywords' => ['speakers', 'panel']],
            ['title' => 'كيف تنضم', 'body' => '[مجانية أو مدفوعة، الرابط، والموعد النهائي إن وجد. كن محددًا.]', 'image_keywords' => ['ticket', 'register']],
            ['title' => 'احجز مكانك', 'body' => '[تذكير أخير + دعوة للرابط في البايو.]', 'image_keywords' => ['phone', 'tap']],
        ],
    ],
    [
        'slug' => 'event_speakers_carousel',
        'category' => 'event',
        'name' => 'كشف متحدثي الفعالية',
        'description' => 'اكشف عن المتحدثين، شريحة لكل واحد.',
        'content' => 'متحدثو [Event Name]. التذاكر متاحة الحين في {{brand_name}}.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'المتحدثون، بالكشف', 'body' => 'قائمة متحدثي [Event Name] بتاريخ [date]. مرر للتعرف عليهم.', 'image_keywords' => ['lineup', 'stage']],
            ['title' => '[المتحدث 1]', 'body' => '[الاسم، الدور. أهم شي رح يتحدث عنه.]', 'image_keywords' => ['portrait', 'speaker']],
            ['title' => '[المتحدث 2]', 'body' => '[الاسم، الدور. موضوع جلسته بسطر وحد.]', 'image_keywords' => ['portrait', 'mic']],
            ['title' => '[المتحدث 3]', 'body' => '[الاسم، الدور. إيش رح يطلع فيه الحضور.]', 'image_keywords' => ['portrait', 'panel']],
            ['title' => 'التذاكر في البايو', 'body' => '[التاريخ، الموقع، ورابط التسجيل.]', 'image_keywords' => ['ticket', 'register']],
        ],
    ],
    [
        'slug' => 'workshop_invitation_carousel',
        'category' => 'event',
        'name' => 'دعوة لورشة عمل',
        'description' => 'ادعُ الناس لورشة عمل تطبيقية.',
        'content' => 'ورشة عمل تطبيقية في {{brand_name}} بتاريخ [date]. المقاعد محدودة، وهذا اللي بيصير.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'ورشة بتاريخ [date]', 'body' => '[الموضوع بسطر وحد. أونلاين أو حضوري، مع الموقع والوقت.]', 'image_keywords' => ['workshop', 'class']],
            ['title' => 'إيش رح تسوي', 'body' => '[ثلاث أنشطة عملية. استخدم أفعالًا، مو صفات.]', 'image_keywords' => ['hands', 'making']],
            ['title' => 'إيش رح تطلع فيه', 'body' => '[الناتج: شي جاهز، مسودة، قرار، أو خطة.]', 'image_keywords' => ['notebook', 'result']],
            ['title' => 'احجز مقعدك', 'body' => '[عدد المقاعد المتبقية، السعر إن وجد، والرابط في البايو.]', 'image_keywords' => ['chair', 'register']],
        ],
    ],
    [
        'slug' => 'this_or_that_carousel',
        'category' => 'engagement',
        'name' => 'هذا أو ذاك',
        'description' => 'اسأل متابعينك سلسلة أسئلة اختيار بين خيارين.',
        'content' => 'هذا أو ذاك، نسخة [topic]. قول لي اختياراتك في التعليقات.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'اختر واحد', 'body' => 'خمس اختيارات سريعة. اكتب إجاباتك بالترتيب في التعليقات.', 'image_keywords' => ['choice', 'fork']],
            ['title' => '[الخيار أ] أو [الخيار ب]', 'body' => '[سياق مختصر إذا احتجت.]', 'image_keywords' => ['split', 'options']],
            ['title' => '[الخيار ج] أو [الخيار د]', 'body' => '[سياق مختصر إذا احتجت.]', 'image_keywords' => ['versus', 'choice']],
            ['title' => '[الخيار هـ] أو [الخيار و]', 'body' => '[سياق مختصر إذا احتجت.]', 'image_keywords' => ['compare', 'pick']],
            ['title' => 'دورك الحين', 'body' => 'اكتب إجاباتك تحت. أنا أقرأ كل تعليق.', 'image_keywords' => ['comment', 'phone']],
        ],
    ],
    [
        'slug' => 'unpopular_opinion_carousel',
        'category' => 'engagement',
        'name' => 'رأي غير شائع',
        'description' => 'شارك رأيًا حقيقيًا وافتح المجال للنقاش.',
        'content' => 'رأي غير شائع عن [topic]. قول لي وين أنا غلطان في التعليقات.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'رأي غير شائع', 'body' => '[الرأي بجملة قصيرة وواضحة.]', 'image_keywords' => ['opinion', 'speech']],
            ['title' => 'ليش أفكر كذا', 'body' => '[السبب. قصة صغيرة أو رقم، مو مجرد مشاعر.]', 'image_keywords' => ['reason', 'thinking']],
            ['title' => 'وين ممكن أكون غلطان', 'body' => '[كن صادقًا حول أضعف نقطة في الفكرة.]', 'image_keywords' => ['doubt', 'question']],
            ['title' => 'قول لي رأيك', 'body' => 'موافق، غير موافق، أو رأي مختلط، اكتبه في التعليقات.', 'image_keywords' => ['comment', 'discussion']],
        ],
    ],
    [
        'slug' => 'fill_in_the_blank_carousel',
        'category' => 'engagement',
        'name' => 'أكمل الفراغ',
        'description' => 'اطرح على متابعينك ثلاث جمل ناقصة يكملونها.',
        'content' => 'أكمل الفراغات. أبغى أقرأ إجاباتك.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'أكمل الفراغات', 'body' => 'ثلاث جمل سريعة عن [topic]. اكتب إجاباتك بالترتيب في التعليقات.', 'image_keywords' => ['blank', 'pen']],
            ['title' => 'الجملة الأولى', 'body' => 'أفضل [الشيء] اللي [الفعل] هالسنة كان ____.', 'image_keywords' => ['idea', 'thought']],
            ['title' => 'الجملة الثانية', 'body' => 'الشي اللي أبغى أسويه أكثر في [topic] هو ____.', 'image_keywords' => ['plan', 'goal']],
            ['title' => 'الجملة الثالثة', 'body' => 'شخص واحد علّمني عن [topic] هو ____.', 'image_keywords' => ['mentor', 'people']],
        ],
    ],
    [
        'slug' => 'q_and_a_carousel',
        'category' => 'engagement',
        'name' => 'كاروسيل أسئلة وأجوبة',
        'description' => 'أجب على خمسة أسئلة حقيقية من جمهورك.',
        'content' => 'أنتم سألتوا وأنا جاوبت. خمسة أسئلة حقيقية من الخاص.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'أسئلة وأجوبتها', 'body' => 'اخترت خمسة من هالأسبوع. أخفيت الهوية عند الحاجة.', 'image_keywords' => ['questions', 'mail']],
            ['title' => 'س1', 'body' => 'س: [إعادة صياغة السؤال]. ج: [الإجابة بجملة أو جملتين].', 'image_keywords' => ['answer', 'note']],
            ['title' => 'س2', 'body' => 'س: [إعادة صياغة السؤال]. ج: [الإجابة].', 'image_keywords' => ['reply', 'speech']],
            ['title' => 'س3', 'body' => 'س: [إعادة صياغة السؤال]. ج: [الإجابة].', 'image_keywords' => ['question', 'mark']],
            ['title' => 'س4', 'body' => 'س: [إعادة صياغة السؤال]. ج: [الإجابة].', 'image_keywords' => ['chat', 'bubble']],
            ['title' => 'س5', 'body' => 'س: [إعادة صياغة السؤال]. ج: [الإجابة]. اكتب المزيد من الأسئلة في التعليقات.', 'image_keywords' => ['comments', 'phone']],
        ],
    ],
];
