<?php

declare(strict_types=1);

return [
    [
        'slug' => 'threads_hot_take',
        'category' => 'industry_tip',
        'name' => 'رأي جريء',
        'description' => 'منشور قصير برأي واضح يحفّز الردود.',
        'content' => "رأي مو شائع: [عبارة غير متوقعة عن مجالك].\n\nوهذا سبب رأيي →\n\n[تفسير مختصر بجملة أو جملتين.]\n\nأنا غلطان؟",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_quick_tip',
        'category' => 'educational',
        'name' => 'نصيحة سريعة',
        'description' => 'نصيحة عملية واحدة بأسلوب قصير وودي.',
        'content' => "نصيحة سريعة من {{brand_name}}:\n\n[نصيحة واحدة محددة وقابلة للتطبيق.]\n\nتبدو بسيطة. بس تغيّر كل شي.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_question',
        'category' => 'engagement',
        'name' => 'سؤال مفتوح',
        'description' => 'اسأل مجتمعك سؤال يفتح نقاش.',
        'content' => "سؤال بصراحة لمجتمع {{brand_name}}:\n\n[سؤال مفتوح ومحدد بما يكفي للإجابة.]\n\nما فيه إجابة غلط. متحمس أشوف ردودكم.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_product_launch_soft',
        'category' => 'product_launch',
        'name' => 'إعلان إطلاق هادئ',
        'description' => 'إعلان بسيط وغير رسمي عن شي جديد صدر.',
        'content' => "طيب بصراحة. أطلقنا [اسم المنتج] اليوم.\n\nكنا شغالين عليه من [مدة زمنية] ومو مصدق إنه صار شغال بالفعل.\n\n[شي محدد يسويه وفخور فيه].\n\nإذا جربته، قول لي وش ما يشتغل.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_product_launch_story',
        'category' => 'product_launch',
        'name' => 'ليش بنيناه',
        'description' => 'قصة شخصية وراء المنتج أو الميزة الجديدة.',
        'content' => "بدأت أبني [اسم المنتج] بسبب [إحباط شخصي محدد].\n\nكنت متوقع إنه ياخذ عطلة نهاية أسبوع بس. أخذ [الوقت الفعلي].\n\nصار متاح الحين في {{brand_name}}. بصراحة لسا مستغرب إنه شغال.\n\nيسعدني أسمع رأيك بعد ما تجربه.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_product_launch_feature',
        'category' => 'product_launch',
        'name' => 'ميزة جديدة',
        'description' => 'إعلان عن ميزة واحدة داخل منتج موجود.',
        'content' => "شي بسيط بس متحمس له بطريقة غريبة.\n\n{{brand_name}} الحين [يسوي هالشي المحدد].\n\nالسبب: الناس كانوا يطلبون [الحاجة الأساسية] باستمرار. فسويناها.\n\nصارت متاحة. جربها وقول لي إذا فعلاً مفيدة أو بس ميزة زيادة.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_promo_discount',
        'category' => 'promotion',
        'name' => 'منشور خصم بسيط',
        'description' => 'طريقة هادئة لذكر عرض أو خصم.',
        'content' => "عندنا خصم [نسبة الخصم] على [المنتج أو الباقة] هالأسبوع في {{brand_name}}.\n\nمو بسوي كل قصة العد التنازلي. بس حبيت أذكرها مرة وأخلي كل واحد يقرر.\n\nالكود: [الكود]. ينتهي [التاريخ].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_promo_bundle',
        'category' => 'promotion',
        'name' => 'عرض باقة',
        'description' => 'الترويج لعرض مجمّع بأسلوب هادئ.',
        'content' => "جمعنا [العنصر الأول] مع [العنصر الثاني] لأن الناس كانوا يشترونهم مع بعض في نفس الطلب أصلاً.\n\nسعر الثنين [السعر] في {{brand_name}}، يعني توفر تقريباً [مبلغ التوفير] عن شرائهم منفصلين.\n\nهذا كل شي. هذا المنشور.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_promo_last_chance',
        'category' => 'promotion',
        'name' => 'تذكير آخر فرصة',
        'description' => 'تذكير ودي بأن العرض بينتهي.',
        'content' => "بس تنبيه: [اسم العرض] بينتهي [التاريخ أو الوقت].\n\nمو أبي أضغط عليكم. بعضكم طلب إني أذكّره، فخذوها تذكير.\n\nالرابط في البايو إذا تبونه. ولا زعل إذا ما تبونه.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_edu_mistake',
        'category' => 'educational',
        'name' => 'غلطة سويتها',
        'description' => 'تعليم من خلال مشاركة غلطة شخصية.',
        'content' => "كررت نفس الغلطة [عدد] مرات قبل ما أفهم هالشي:\n\n[الغلطة بجملة وحدة].\n\nالحل [الحل الفعلي بكلمات بسيطة]. ما فيه شي معقد. بس كان لازم أوقف عن سوي هالشي.\n\nأنشره لأنه ممكن تكون عالق بنفس الدوامة.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_edu_misconception',
        'category' => 'educational',
        'name' => 'فكرة خاطئة شائعة',
        'description' => 'تصحيح فكرة منتشرة بس غلط.',
        'content' => "الناس دايم يقولون لي [فكرة شائعة في مجالك].\n\nهذا مو كيف يشتغل الوضع.\n\n[اللي يصير فعلياً، بكلمات بسيطة].\n\nممكن يكون واضح لبعضكم. بس مو واضح لأغلب اللي راسلوني الأسبوع الماضي.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_edu_resource',
        'category' => 'educational',
        'name' => 'مشاركة مصدر',
        'description' => 'ترشيح مصدر مفيد مع سياق شخصي.',
        'content' => "إذا تحاول تتعلم [الموضوع]، بطّل تتفرج على فيديوهات يوتيوب أربع ساعات وبس اقرأ [المصدر المحدد].\n\nأجّلته أشهر لأن عنوانه ممل. بس هو الشي الوحيد اللي فعلاً فهمته منه صح.\n\nهذا الترشيح.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_edu_step_breakdown',
        'category' => 'educational',
        'name' => 'شرح سريع',
        'description' => 'خطوات صغيرة بأسلوب حواري.',
        'content' => "موضوع [المهمة] في 4 أسطر لكل واحد يسأل عنه باستمرار:\n\n1. [الخطوة الأولى]\n2. [الخطوة الثانية]\n3. [الخطوة الثالثة]\n4. [الخطوة الرابعة]\n\nهذي العملية كاملة. ما تحتاج دورة عشانها.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_bts_morning',
        'category' => 'behind_the_scenes',
        'name' => 'روتين الصباح',
        'description' => 'لمحة بسيطة عن بداية يوم العمل.',
        'content' => "اليوم في {{brand_name}}:\n\n- قهوة\n- حدّقت في [مشكلة محددة] لمدة ساعة\n- اكتشفت إن الخطأ في السطر [رقم]\n- صلحته في 4 دقايق\n\nنسبة التفكير مقابل التنفيذ في هالشغلة ملعونة فعلاً.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_bts_decision',
        'category' => 'behind_the_scenes',
        'name' => 'قرار اتخذناه',
        'description' => 'مشاركة قرار داخلي مع سبب اتخاذه.',
        'content' => "قررنا [قرار محدد] هالأسبوع.\n\nالخيار الثاني كان [البديل]. نص الفريق كان يبيه. وأنا لسا شوي أبيه.\n\nبس [السبب الفعلي اللي رجّح هالقرار].\n\nاسألني بعد 3 أشهر إذا كان القرار الصح.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_bts_messy_progress',
        'category' => 'behind_the_scenes',
        'name' => 'لقطة تقدم غير مرتبة',
        'description' => 'تحديث صادق في منتصف المشروع.',
        'content' => "الوضع الحالي لـ [اسم المشروع]:\n\n- [نسبة] مكتمل\n- [شي محدد يشتغل]\n- [شي محدد ما يشتغل]\n- [عدد] تابات مفتوحة أخاف أسكرها\n\nبنطلقه لما يوقف يحرجني.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_bts_team_moment',
        'category' => 'behind_the_scenes',
        'name' => 'لحظة من الفريق',
        'description' => 'لحظة إنسانية بسيطة من الفريق.',
        'content' => "[اسم في الفريق] أرسل رسالة على السلاك تقول \"[اقتباس قصير طريف أو ذكي]\" والحين ما نبطل نكررها.\n\nبناء {{brand_name}} مع هالناس نص السبب إني لسا أحب هالشغلة.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_testimonial_quote',
        'category' => 'testimonial',
        'name' => 'اقتباس من عميل',
        'description' => 'مشاركة كلام حقيقي من عميل مع سياق بسيط.',
        'content' => "وصلني هالإيميل من [الاسم الأول أو الأحرف] أمس:\n\n\"[اقتباس مباشر من العميل، جملة أو جملتين]\"\n\nقريتها مرتين. هذا الجزء من الشغل اللي ما يظهر في الأرقام.\n\nشكراً لاستخدامك {{brand_name}}. من قلبي.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_testimonial_outcome',
        'category' => 'testimonial',
        'name' => 'نتيجة عميل',
        'description' => 'الحديث عن نتيجة حقيقية لعميل بدون مبالغة.',
        'content' => "[الاسم الأول للعميل] قال لي أمس إنه [نتيجة محددة] بعد ما استخدم {{brand_name}} لمدة [فترة زمنية].\n\nما طلبت منه يشاركها. بس أرسل لي سكرين شوت وقال \"حسيت إنك تحب تشوف هذا.\"\n\nصح. أحببته.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_testimonial_unexpected',
        'category' => 'testimonial',
        'name' => 'استخدام غير متوقع',
        'description' => 'تسليط الضوء على طريقة استخدام مفاجئة للمنتج.',
        'content' => "ما توقعت هذا أبداً.\n\nفيه واحد يستخدم {{brand_name}} في [استخدام غير متوقع]. مو اللي بنيناه من أجله. بس يبدو إنه يشتغل.\n\nأحلى جزء من إطلاق الأشياء إنك تكتشف وش الناس فعلاً يسوون فيها.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_industry_observation',
        'category' => 'industry_tip',
        'name' => 'ملاحظة عن المجال',
        'description' => 'مشاركة نمط تلاحظه باستمرار في مجالك.',
        'content' => "شي ألاحظه باستمرار في [المجال]:\n\n[ملاحظة محددة بجملة وحدة].\n\nممكن يكون تحول حقيقي. وممكن يكون بس انحياز في اختيار مين أتكلم معه. قول لي إذا تلاحظه أنت كذلك.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_industry_lesson',
        'category' => 'industry_tip',
        'name' => 'درس من التجربة',
        'description' => 'درس واحد تعلمته بصعوبة، بدون حشو.',
        'content' => "[عدد] سنوات في [المجال] والدرس اللي أخذت وقت طويل عشان أصدقه فعلاً:\n\n[الدرس بجملة وحدة].\n\nلسا ألقى نفسي أتجاهله أحياناً. بعدين شي يتعطل. بعدين أتذكر.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_industry_pushback',
        'category' => 'industry_tip',
        'name' => 'رد على الحكمة السائدة',
        'description' => 'اختلاف مؤدب مع نصيحة شائعة.',
        'content' => "النصيحة المعتادة في [المجال] هي [نصيحة شائعة].\n\nأنا أسوي العكس من [فترة زمنية]. وبصراحة تشتغل أحسن معي.\n\n[سبب مختصر].\n\nمو قاصد إن الكل لازم يسوي كذا. بس أقول القاعدة مو قاعدة.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_industry_prediction',
        'category' => 'industry_tip',
        'name' => 'توقع هادئ',
        'description' => 'طرح توقع بدون مبالغة أو استعراض.',
        'content' => "توقع بسيط:\n\nخلال [إطار زمني]، بيصير [تغيير محدد في مجالك] شي عادي.\n\nممكن أكون غلطان تماماً. بحفظ هذا عشان أرجع له وأضحك على نفسي بعدين.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_event_announcement',
        'category' => 'event',
        'name' => 'إعلان فعالية',
        'description' => 'إعلان بسيط عن فعالية قادمة.',
        'content' => "{{brand_name}} بيسوي [اسم الفعالية] بتاريخ [التاريخ].\n\n[جملة أو جملتين عن وش هي فعلاً ومين بيهتم فيها].\n\n[الموقع أو الرابط]. قول لصديقك إذا حسيت تناسبه.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_event_recap',
        'category' => 'event',
        'name' => 'ملخص الفعالية',
        'description' => 'ملخص صادق بعد فعالية.',
        'content' => "رجعت من [اسم الفعالية].\n\nأحلى جزء كان [لحظة أو محادثة محددة].\n\nأغرب جزء كان [ملاحظة صادقة].\n\nإذا كنت هناك وما تكلمنا، راسلني. دايم فيه كلام أكثر بعد ما تنتهي الجلسة.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_event_invite',
        'category' => 'event',
        'name' => 'دعوة شخصية',
        'description' => 'دعوة مباشرة تحس فيها شخصية.',
        'content' => "بنسوي [نوع الفعالية] صغيرة لـ {{brand_name}} بتاريخ [التاريخ] وفعلاً أبيك تحضر.\n\nمدتها [المدة] وبنتكلم عن [موضوع محدد].\n\nسجل في [الرابط] إذا تبي تنضم. حاطين حد أقصى [العدد] عشان تضل نقاش حقيقي.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_engagement_recommendation',
        'category' => 'engagement',
        'name' => 'طلب ترشيح',
        'description' => 'طلب ترشيحات من الجمهور.',
        'content' => "أبحث عن ترشيحات:\n\n[شي محدد تحتاج ترشيحات له].\n\nجربت قبل [الخيار أ] و[الخيار ب]. أحتاج شي [قيد محدد].\n\nأفضل رد بياخذ امتناني الأبدي. هذي الجائزة.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_engagement_this_or_that',
        'category' => 'engagement',
        'name' => 'هذا أو ذاك',
        'description' => 'سؤال ثنائي سريع يحفّز الردود.',
        'content' => "[الخيار أ] أو [الخيار ب].\n\nما فيه حل وسط. ولا \"يعتمد.\" اختر واحد وقول لي ليش.\n\nهذا النقاش دائر عندنا في {{brand_name}} على شات الفريق ومنقسمين بشدة.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_engagement_confession',
        'category' => 'engagement',
        'name' => 'اعتراف بسيط',
        'description' => 'مشاركة شي بسيط يقدر الكل يتفاعل معه.',
        'content' => "اعتراف بسيط.\n\nلسا [عادة محرجة شوي متعلقة بشغلك أو حياتك].\n\nقول لي إني مو الوحيد. أو قول لي إني الوحيد. بأي حال أبي أعرف.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
