<?php

declare(strict_types=1);

return [
    [
        'slug' => 'flash_sale',
        'category' => 'promotion',
        'name' => 'عرض خاطف',
        'description' => 'منشور قصير في إكس لعرض خاطف بإحساس الاستعجال.',
        'content' => "🔥 عرض خاطف في {{brand_name}}!\n\nخصم [Discount]% على [product/service]، ينتهي خلال 24 ساعة.\n\nبدون كود → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'success_story',
        'category' => 'testimonial',
        'name' => 'قصة نجاح',
        'description' => 'صيغة مختصرة لقصة نجاح على إكس.',
        'content' => "\"[Short customer quote.]\"\n- @[handle]\n\nعشان كذا نسوي اللي نسويه في {{brand_name}}. 🙌",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'this_or_that_poll',
        'category' => 'engagement',
        'name' => 'هذا أو ذاك',
        'description' => 'زد التفاعل بسؤال بسيط بين خيارين.',
        'content' => "سؤال سريع لمجتمع {{brand_name}}:\n\n[Option A] ولا [Option B]؟\n\nرد باختيارك وسبب اختيارك 👇",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'shipped_today',
        'category' => 'product_launch',
        'name' => 'أطلقناه اليوم',
        'description' => 'إعلان بسيط عن إطلاق تحديث محدد.',
        'content' => "أطلقنا اليوم: [feature].\n\nتقدر بها [one specific thing] عشان توقف [annoying workaround].\n\nمتوفرة الحين في {{brand_name}}.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'new_feature_one_liner',
        'category' => 'product_launch',
        'name' => 'ميزة جديدة بسطر واحد',
        'description' => 'جملة واحدة تعرّف بميزة جديدة.',
        'content' => "{{brand_name}} الحين [does specific thing].\n\nإذا كنت [doing painful workaround]، جربها: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'beta_invite',
        'category' => 'product_launch',
        'name' => 'دعوة للتجربة التجريبية',
        'description' => 'دعوة مفتوحة للمشاركة في التجربة التجريبية.',
        'content' => "بنفتح النسخة التجريبية لـ [feature] هالأسبوع.\n\nنبي [number] أشخاص يسوون [specific use case].\n\nرد إذا كنت أنت هذا الشخص.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'finally_built_it',
        'category' => 'product_launch',
        'name' => 'أخيرًا سويناها',
        'description' => 'نبرة صادقة لإطلاق تأخر شوي.',
        'content' => "أخيرًا سوينا [feature]. الناس تطلبها من [time period].\n\nمتوفرة اليوم في {{brand_name}}. آسفين على التأخير.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'weekend_deal',
        'category' => 'promotion',
        'name' => 'عرض نهاية الأسبوع',
        'description' => 'منشور خصم خاص بنهاية الأسبوع فقط.',
        'content' => "نهاية الأسبوع بس: خصم [discount] على [product] في {{brand_name}}.\n\nكود [CODE]. ينتهي الأحد منتصف الليل. وهذا كل شي.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'free_shipping',
        'category' => 'promotion',
        'name' => 'شحن مجاني',
        'description' => 'إعلان عن فترة شحن مجاني.',
        'content' => "شحن مجاني على كل طلب من {{brand_name}} فوق \$[amount] هالأسبوع.\n\nبدون كود، وبدون شروط خفية. يرجع الوضع الطبيعي يوم الاثنين.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'last_call',
        'category' => 'promotion',
        'name' => 'آخر فرصة',
        'description' => 'الساعات الأخيرة من التخفيضات.',
        'content' => "آخر فرصة. [Sale name] ينتهي الليلة الساعة [time].\n\nإذا كان {{brand_name}} في سلتك، هذا أرخص سعر له هالسنة: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bundle_offer',
        'category' => 'promotion',
        'name' => 'عرض الباقة',
        'description' => 'يقدّم باقة منتجات كعرض توفير.',
        'content' => "باقة جديدة في {{brand_name}}: [Product A] + [Product B] بسعر [price].\n\nهذا أوفر بـ [amount] من شرائهم منفصلين. الكمية محدودة بـ [quantity] قطعة.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'one_thing_we_learned',
        'category' => 'educational',
        'name' => 'شي تعلمناه',
        'description' => 'شارك درسًا واحدًا محددًا.',
        'content' => "شي تعلمناه في {{brand_name}} هالشهر:\n\n[Specific finding]. كنا نعتقد [old assumption]، لكن [data point] أثبتت العكس.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'common_mistake',
        'category' => 'educational',
        'name' => 'غلطة شائعة',
        'description' => 'نبّه على غلطة واحدة يقع فيها الناس.',
        'content' => "أغلب الناس يخطئون في [topic] لأنهم [common mistake].\n\nاللي ينفع فعلًا: [counter-approach]. جربناها على [number] عميل.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'quick_tip',
        'category' => 'educational',
        'name' => 'نصيحة سريعة',
        'description' => 'نصيحة صغيرة قابلة للتطبيق.',
        'content' => "نصيحة سريعة إذا كنت تستخدم {{brand_name}}:\n\n[Specific action] قبل [step]. توفر تقريبًا [time/result] لأغلب الناس.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'myth_vs_reality',
        'category' => 'educational',
        'name' => 'خرافة مقابل حقيقة',
        'description' => 'فنّد خرافة واحدة شائعة في المجال.',
        'content' => "خرافة: [common belief about topic].\n\nالحقيقة: [counter-fact with number]. نشوفها في بيانات {{brand_name}} كل أسبوع.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'how_we_built_it',
        'category' => 'behind_the_scenes',
        'name' => 'كيف سويناها',
        'description' => 'نظرة بسيطة من خلف الكواليس.',
        'content' => "كيف سوينا [feature] في {{brand_name}}:\n\nبدأنا بـ [first attempt]. تعطلت. تحولنا لـ [approach 2]. وأطلقناها.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'team_at_work',
        'category' => 'behind_the_scenes',
        'name' => 'الفريق في الشغل',
        'description' => 'لقطة سريعة عن اللي يسويه الفريق الحين.',
        'content' => "اللي فريق {{brand_name}} يشتغل عليه الحين:\n\n[Person/role] يحل مشكلة [specific issue]. [Person/role] يشتغل على [other project]. عدد أكواب القهوة: مرتفع.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mistake_we_made',
        'category' => 'behind_the_scenes',
        'name' => 'غلطة سويناها',
        'description' => 'تحليل صادق للخطأ بتغريدة واحدة.',
        'content' => "غلطنا في {{brand_name}} الأسبوع اللي راح.\n\n[What broke]. سبب [impact] لـ [number] عميل. صلحناها عن طريق [how]. آسفين لكل من تأثر.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'office_moment',
        'category' => 'behind_the_scenes',
        'name' => 'لحظة من المكتب',
        'description' => 'لقطة إنسانية بسيطة من المكتب.',
        'content' => "لحظة عشوائية من مكتب {{brand_name}}:\n\n[Specific scene, e.g. designer arguing with engineer over a 2px button radius]. وهذا حال أغلب الأيام بصراحة.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'customer_dm',
        'category' => 'testimonial',
        'name' => 'رسالة من عميل',
        'description' => 'شارك رسالة حقيقية من عميل.',
        'content' => "وصلتنا هالرسالة من عميل في {{brand_name}} اليوم:\n\n\"[Short quote about what changed for them].\"\n\nهذا الجزء من الشغل اللي ما يمل أبدًا.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'before_and_after',
        'category' => 'testimonial',
        'name' => 'قبل وبعد',
        'description' => 'أرقام محددة قبل وبعد من تجربة عميل.',
        'content' => "[Customer name] قبل {{brand_name}}: [metric].\n\n[Customer name] بعد [time period]: [new metric].\n\nولا شي ثاني تغير في إعدادهم.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'one_line_review',
        'category' => 'testimonial',
        'name' => 'تقييم بسطر واحد',
        'description' => 'جملة قصيرة واحدة من عميل.',
        'content' => "\"[Specific customer line, max 12 words.]\"\n\n- [Customer name]، [role] في [company]\n\nما طلبنا منهم يكتبون هذا.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'hot_take',
        'category' => 'industry_tip',
        'name' => 'رأي جريء',
        'description' => 'رأي واضح عن المجال.',
        'content' => "رأي جريء: أغلب الناس في [industry] يعتقدون [common belief].\n\nبعد [time] من إدارة {{brand_name}}، أنا أرى العكس. [Specific reason].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'overrated_underrated',
        'category' => 'industry_tip',
        'name' => 'مبالغ فيه وغير مقدّر',
        'description' => 'قارن بين شي مبالغ فيه وشي غير مقدّر.',
        'content' => "مبالغ فيه في [industry]: [common practice].\n\nغير مقدّر بما فيه الكفاية: [overlooked practice].\n\nوقفنا عن الأولى في {{brand_name}} من سنة.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'unpopular_opinion',
        'category' => 'industry_tip',
        'name' => 'رأي غير شائع',
        'description' => 'شارك ملاحظة مخالفة للسائد.',
        'content' => "رأي غير شائع: [contrarian statement about industry].\n\nعملاء {{brand_name}} يثبتون هذا كل شهر. والبيانات واضحة جدًا.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'what_changed_my_mind',
        'category' => 'industry_tip',
        'name' => 'الشي اللي غيّر رأيي',
        'description' => 'لحظة صادقة لتغيّر الرأي.',
        'content' => "كنت أعتقد [old belief about industry].\n\nبعدين صار [specific event/data] في {{brand_name}}. الحين أرى [new view]. وما زلت أتكيف.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'event_announcement',
        'category' => 'event',
        'name' => 'إعلان فعالية',
        'description' => 'إعلان بسيط عن فعالية.',
        'content' => "{{brand_name}} يستضيف [event name] بتاريخ [date] في [city].\n\n[Specific topic]. مجانًا، [capacity] مقعد. سجل: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'event_recap',
        'category' => 'event',
        'name' => 'ملخص الفعالية',
        'description' => 'ملخص قصير بعد الفعالية.',
        'content' => "[Number] شخص حضروا [event] الخاصة بـ {{brand_name}} الليلة اللي راحت.\n\nأفضل سؤال: \"[real audience question].\" التسجيل ينزل يوم الجمعة.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'webinar_reminder',
        'category' => 'event',
        'name' => 'تذكير بالندوة الإلكترونية',
        'description' => 'تذكير بندوة إلكترونية قريبة.',
        'content' => "تذكير: ندوة {{brand_name}} الإلكترونية عن [topic] تبدأ خلال [time].\n\n[Speaker] بيشرح [specific thing]. آخر فرصة للتسجيل: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'open_question',
        'category' => 'engagement',
        'name' => 'سؤال مفتوح',
        'description' => 'اسأل الجمهور سؤالًا حقيقيًا.',
        'content' => "سؤال حقيقي لكل من يستخدم [tool/category]:\n\nإيش الشي الوحيد اللي ما زال ما يقدر يسويه وتتمنى يقدر عليه؟\n\nنسأل لأننا نشتغل عليه في {{brand_name}}.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'fill_in_the_blank',
        'category' => 'engagement',
        'name' => 'أكمل الفراغ',
        'description' => 'سؤال بسيط بصيغة أكمل الفراغ.',
        'content' => "أكمل الفراغ:\n\nأسوأ شي في [task/topic] هو ______.\n\nبنقرأ كل رد. بنستخدمها في تخطيط الربع القادم لـ {{brand_name}}.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'show_us_your_setup',
        'category' => 'engagement',
        'name' => 'أرونا إعدادكم',
        'description' => 'اطلب من الناس مشاركة شي مرئي.',
        'content' => "أرونا [thing, desk, dashboard, weekly routine].\n\nبننشر أفضل ثلاثة نختارهم على حساب {{brand_name}} الأسبوع الجاي. بدون فلاتر.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
